In [3]:
string=""" hey my name is arman hossain  , i want to dream in abroad . i alaways feel hasitation because I do
dont know that i can do it"""
print(string)

 hey my name is arman hossain  , i want to dream in abroad . i alaways feel hasitation because I do
dont know that i can do it

In [4]:
idx=string.find("arman")
print(idx)

16

#it there is a multiple string i want to see at last string of this multiple string

In [5]:
id=string.rfind("do")
print(id)

121

In [6]:
count=string.count("do")
print(count)

3

In [7]:
replace=string.replace("do","must")
print(replace)

 hey my name is arman hossain  , i want to dream in abroad . i alaways feel hasitation because I must
mustnt know that i can must it

#tokennization

#spliting,joining,formatted string

In [8]:
for x in "banana":
  print(x)

b
a
n
a
n
a

In [9]:
len=len(string)
print(len)

126

In [10]:
txt="the best things in life are free"
print("free" in txt)

True

In [11]:
if "arman" in txt:
    print("yes baby its here ")

else:
    print("no baby its not here  search another things ")

no baby its not here  search another things

In [12]:
print("arman" not in txt)

True

In [13]:
message=""" hello Iam recenty join the 
course of python AI/ml course """
a=message
print(a.upper())
print(a.lower())
print(a.capitalize())

 HELLO IAM RECENTY JOIN THE
COURSE OF PYTHON AI/ML COURSE
 hello iam recenty join the
course of python ai/ml course
 hello iam recenty join the
course of python ai/ml course

এর মানে — যদি তোমার কোনো স্ট্রিং-এর শুরুতে বা শেষে অতিরিক্ত স্পেস বা কিছু নির্দিষ্ট চিহ্ন থাকে, তাহলে strip() সেগুলো সরিয়ে দেয়।

In [14]:
ar="                       \r\f my name is Arman \n  "
print(ar.strip())

my name is Arman

In [15]:
name = input("Enter your name: ")  # ধরো ইনপুট: "  Arman  "
clean_name = name.strip()
print("Welcome,", clean_name)

Welcome, 56

Problem 1: Common Friends (Set Operations)
Problem:
 Given two sets of friends from two people, find the mutual friends, unique friends of each, and the total number of unique friends.\n

Example Input:

a_friends = {"Rahim", "Karim", "Sakib", "Jamal"}

b_friends = {"Sakib", "Jamal", "Rafiq", "Nadim"}

Expected Output:

Mutual friends: {'Sakib', 'Jamal'}

Unique to A: {'Rahim', 'Karim'}

  Unique to B: {'Rafiq', 'Nadim'}

Total unique friends: 6

In [16]:
a_friends = {"Rahim", "Karim", "Sakib", "Jamal"}
b_friends = {"Sakib", "Jamal", "Rafiq", "Nadim"}
c=a_friends.intersection(b_friends)
print("Mutual friends is : ",c)
d=a_friends.difference(b_friends)
print("Unique to A:",d)
e=b_friends.difference(a_friends)
totall_unique=a_friends.union(b_friends)
print(totall_unique)
totall=len(totall_unique)
print("Totall unique name is :",totall)

Mutual friends is :  {'Jamal', 'Sakib'}
Unique to A: {'Rahim', 'Karim'}
{'Jamal', 'Sakib', 'Karim', 'Nadim', 'Rafiq', 'Rahim'}

TypeError: 'int' object is not callable

list method in python and also list concatanation

In [ ]:
even=[]

for i in range(10):
    if i%2==0:
        even.append(i)

print(even)

[0, 2, 4, 6, 8]

same things we can do in list comprehension

In [ ]:
even=[x for x in range(10) if x%2==0]
print(even)

[0, 2, 4, 6, 8]

In [ ]:
fruits=["banana",'orange','mango','lemon']
c=[]
for i in fruits:
 c.append(i.capitalize())

print(c)

['Banana', 'Orange', 'Mango', 'Lemon']

but in list compression we can do it  in a simple way

In [ ]:
lower=[fruit.lower() for fruit in fruits]
print(lower)

['banana', 'orange', 'mango', 'lemon']

In [ ]:
upper=[fruit.upper() for fruit in fruits]
print(upper)

['BANANA', 'ORANGE', 'MANGO', 'LEMON']

In [ ]:
promt="what is life guys "
token=promt.split()
print(token)

for i in token:
    print(i)

string=" ".join(token)
print(string)

['what', 'is', 'life', 'guys']
what
is
life
guys
what is life guys

here we take input as a list y using split ()

In [ ]:
n=input("ente a string : ")

a=n.split()
print(a)

['hu', 'mt', 'name', 'is', 'arman', 'hossain', 'shawon']

list method

In [ ]:
lst=[10,20,30,40,50,60]
lst.append(80)

print(lst)

lst.insert(0,100)
print(lst)
lst.pop(0)#give here index value not given value 
print(lst)
lst.sort()
print(lst)
lst.reverse()
print(lst)
lst.remove(10)
print(lst)
print(lst[0])

[10, 20, 30, 40, 50, 60, 80]
[100, 10, 20, 30, 40, 50, 60, 80]
[10, 20, 30, 40, 50, 60, 80]
[10, 20, 30, 40, 50, 60, 80]
[80, 60, 50, 40, 30, 20, 10]
[80, 60, 50, 40, 30, 20]
80

TUPLE

IN Python

In [ ]:
tuo=(10,23,'arman',True)
print(tuo)
tuo[0]=100
print(tuo)#tuple  are immautable

(10, 23, 'arman', True)

TypeError: 'tuple' object does not support item assignment

dictionary in python and it a method and iteration

Dictionay view method in python

In [ ]:
dic={'ID':231061008,'name':'arman','age':20}
key=dic.keys()
print(key)
print(dic.values())
for key,value in dic.items():
    print(key,value)

dict_keys(['ID', 'name', 'age'])
dict_values([231061008, 'arman', 20])
ID 231061008
name arman
age 20

In [ ]:
#dictionanry comprehension
square={x:x**2 for x in range(10)if x%2==0}
print(square)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

In [ ]:
co=[(10,20,30),(30,56,89),(45,56,90)]
lo=['Dhaka','comilla','uk']
exact_location={cor:loc for cor,loc in zip(co,lo) }
print(exact_location)
print(co)

{(10, 20, 30): 'Dhaka', (30, 56, 89): 'comilla', (45, 56, 90): 'uk'}
[(10, 20, 30), (30, 56, 89), (45, 56, 90)]

given a string  print the freguncy of the word

In [ ]:
message="""Hi my name is Arman . Recently I learn about machine learning so i decided to learn python basic """
words=message.split()
print(words)#creat this string into token

['Hi', 'my', 'name', 'is', 'Arman', '.', 'Recently', 'I', 'learn', 'about', 'machine', 'learning', 'so', 'i', 'decided', 'to', 'learn', 'python', 'basic']

In [ ]:
count={}
for word in words:
    count[word]=count.get(word,0)+1
print(count)

{'Hi': 1, 'my': 1, 'name': 1, 'is': 1, 'Arman': 1, '.': 1, 'Recently': 1, 'I': 1, 'learn': 2, 'about': 1, 'machine': 1, 'learning': 1, 'so': 1, 'i': 1, 'decided': 1, 'to': 1, 'python': 1, 'basic': 1}

In [ ]:
lst=[1,23,45,67,78,3,56]
lst.sort(reverse=True)#decending order print korbe boro theke choto 
print(lst)
lst.sort()
print(lst)

[78, 67, 56, 45, 23, 3, 1]
[1, 3, 23, 45, 56, 67, 78]

Problem 2: Sort Students by Marks (Tuple + Dictionary)
Problem:
 You are given a list of tuples — each containing a student’s name and mark.
 Sort them in descending order of marks and print the top 3 scorers.
Example Input:
students = [("Rafi", 89), ("Sumi", 95), ("Hasan", 90), ("Nila", 75), ("Anik", 98)]

Expected Output:
Top 3 students:
Anik - 98
Sumi - 95
Hasan - 90

In [ ]:
students = [("Rafi", 89), ("Sumi", 95), ("Hasan", 90), ("Nila", 75), ("Anik", 98)]

# Step 1: Convert list of tuples into a dictionary
marks_dict = dict(students)
print(marks_dict)

# Step 2: Prepare for sorting
sorted_students = []
for name, mark in marks_dict.items():
    sorted_students.append([mark, name])  # put mark first
print(sorted_students)

sorted_students.sort(reverse=True)  # sort descending by mark

# Step 3: Print top 3
print("Top 3 students:")
for i in range(3):
    mark, name = sorted_students[i]
    print(f"{name} - {mark}")

{'Rafi': 89, 'Sumi': 95, 'Hasan': 90, 'Nila': 75, 'Anik': 98}
[[89, 'Rafi'], [95, 'Sumi'], [90, 'Hasan'], [75, 'Nila'], [98, 'Anik']]
Top 3 students:
Anik - 98
Sumi - 95
Hasan - 90

In [ ]:
#function 

#unpacking 
def greet():
    a=[10,90,89,78]
    b=[34,67,45,34]

    return a,b

#unpacking
x,y=greet()
print(x,y)

[10, 90, 89, 78] [34, 67, 45, 34]

iterator in python

In [ ]:
lst = [10,20,30,40,50,60,70,80,90,100]
my_iter = iter(lst)
print(next(my_iter))
print(next(my_iter))

10
20

generator in python

In [ ]:
def data_loader(size,lst):
    for i in range(0,len(lst),size):
        yield lst[i:i+size]
lst=[x for x in range(100)]
x=data_loader(5,lst)
print(next(x))
print(next(x))
#in a specific portion we want to see by generator

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

In [ ]:
def data(size,lst):
    for i in range(0,len(lst),size):
        yield lst[i:i+size]
lst=[x for x in range(50)]
x=data(5,lst)
print(next(x))
print(next(x))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

lambda function

In [ ]:
#normal way 
def square(a):
    return a**2
print(square(3))

9

In [ ]:
#same things we can do by lanbda function here we dont want to return anythings 

square=lambda x:x**2
print(square(3))

9

In [ ]:
if_even=lambda x:x%2==0
print(if_even(4))

True

MAP

In [ ]:
#multiple input with map function
a,b,c=map(int,input("enter three numbers :").split())
print(a,b,c)

45 45 67

In [ ]:
lst = [12, 34, 57]

def square(x):
    return x**2

lst = list(map(square, lst))  # function এবং iterable আলাদা আর্গুমেন্ট
print(lst)

[144, 1156, 3249]

In [ ]:
lst=[1,2,3,4,5,6,7]
lst1=list(map(lambda x:x**2 if x%2==0 else x,lst))
print(lst1)

[1, 4, 3, 16, 5, 36, 7]

Filter in python

In [ ]:
num=[x for x in range(20)]
print(num)
even=list(filter(lambda x:x%2==0,num))
print(even)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
l=["arman","showon","dhaka","bangladesh"]

lst=list(filter(lambda x: len(x)>4,l))
print(lst)

['arman', 'showon', 'dhaka', 'bangladesh']

Problem 3: Word Length Filter (Lambda + Filter)

Problem:

 Given a list of words, use filter() and lambda to return only words whose length is greater than 4.

 Example Input:

words = ["sun", "planet", "moon", "star", "universe"]


Expected Output:

['planet', 'universe']

In [ ]:
words = ["sun", "planet", "moon", "star", "universe"]
lst=list(filter(lambda x: len(x)>4,words))
print(lst)

['planet', 'universe']

Problem 4: Square of Even Numbers (Map + Filter + Lambda)
Problem:
 Write a one-line Python expression using map(), filter(), and lambda that takes a list of integers and returns the squares of even numbers only.
Example Input:
nums = [1, 2, 3, 4, 5, 6]

Expected Output:
[4, 16, 36]

In [ ]:
nums = [1, 2, 3, 4, 5, 6]
result = list(map(lambda x: x**2, filter(lambda x: x % 2 == 0, nums)))
print(result)

[4, 16, 36]

In [ ]:
s="arman"

vowel=list(filter(lambda x: x in "aeiou",s))
print(vowel)

['a', 'a']

In [ ]:
fruits=["apple","banana","lichi","mango"]

fr=list(filter(lambda x:len(x)>2,fruits))
print(fruits)

['apple', 'banana', 'lichi', 'mango']

reduce in python

In [ ]:
from functools import reduce

lst=[12,34,56,23,56,78,3333]

sum=reduce(lambda x,y: x+y,lst)
print(sum)

3592

In [ ]:
max=reduce(lambda x,y: x if x>y else y,lst)
print(max)

3333

In [ ]:
str=['hello','Arman']
con=reduce(lambda x,y:x+ " "+y,str)
print(con)

hello Arman

Exception handeling (Error handeling)

In [ ]:
try:
 a=int(input("enter a number :"))
 print(f"Multipication table of{a} is :")
 for i in range(1,11):
    print(f"{a}*{i}={a*i}")
except Exception as e:
 print("some input error")

 print("the code is run successfully")
print("there is no error in this code")

some input error
the code is run successfully
there is no error in this code

Finally in python with file handeling concept

In [ ]:
# model train


try:
  file = open("data1.txt","r")
except Exception as e:
  print(e)
else:
  # model train
  print(file.read())
finally:
  print("Gpu is stopped")

[Errno 2] No such file or directory: 'data1.txt'
Gpu is stopped

Raising custom error in python

In [ ]:
a=int(input("enter a number between 5 and 9 :"))

if a<5 and a>9:
    raise ValueError("Value should be between 5 and 9")

print(a)

4

OOP IN PYTHON PROGRAMMING LANGUAGE |

CLASS AND CLASS OBJECT

CLASS ATTRIBUTE AND INSTANCE ATTRIBUTE

class attribute

In [ ]:
class Phone:
    catagory="electronics"

apple=Phone()
print(apple.catagory)

electronics

instance attributes

In [ ]:
class Phone:
    def __init__(self,model,battery,camera,battery_charge=100):
        self.model=model
        self.battery=battery
        self.camera=camera
        self.battery_charge=battery_charge
apple=Phone("abc",10000,34)
print(apple.battery)
print(apple.battery_charge)
print(apple.camera)
print(apple.model)

10000
100
34
abc

Method in class

In [ ]:
class Phone:
    def __init__(self,model,battery,camera,battery_charge=100):
        self.model=model
        self.battery=battery
        self.camera=camera
        self.battery_charge=battery_charge

    def charge(self,hour):
        self.battery_charge +=hour
        print(f'charge completed by {hour}')

    def capture(self,totall_photo):
        if(self.battery_charge)<=0:
            print("No charge")
        else:
            self.battery_charge-=totall_photo
            print(f"Photo capture in {self.model}")    

apple=Phone("abc",10000,34)
apple.capture(-12)
print(apple.battery_charge)

Photo capture in abc
112

Inheritance

#childclass

In [ ]:
class smartPhone(Phone):
    def __init__(self,model,battery,camera,processor):
        super(). __init__(model,battery,camera)#here we dont need to self paremeter

        self.processor=processor

    def charge(self,hour):
        print("first charging in process")
        super().charge (hour)



pro=smartPhone("ww",5000,100,"snapDragon")

print(pro.model)
pro.charge(1)

ww
first charging in process
charge completed by 1

multiple inheritance

In [ ]:
class Colling_Mechanism:
    def __init__(self,colling_method):
        self.colling_method=colling_method

#method
    def coling_on(self):
        print(f'the system is being cool by {self.colling_method}')

In [ ]:
class smartphonWithCooling_mood(smartPhone,Colling_Mechanism):
    def __init__(self,model,battery,camera,processor,cooling_method):

        smartPhone. __init__(self,model,battery,camera,processor)
        Colling_Mechanism. init__(self,cooling_method)

In [ ]:
proColling=smartphonWithCooling_mood("y", 5000, 100, 'sD', "liquid")

TypeError: 'tuple' object is not callable

oop mini project

balance

name

ac_no

In [ ]:
promt=input()
token=promt.split()
print(token)
even=list(filter(lambda x:x%2==0,token))
print(even)

['1', '3', '4', '5', '6', '6']

TypeError: not all arguments converted during string formatting

Using filter() and lambda, extract even numbers from a given list.
Input Format:
 Integers separated by space.
Output Format:
 List of even integers.
Example:
Input: 5 6 7 8 9 10  
Output: [6, 8, 10]

In [ ]:
lst=input()
token=lst.split()
print(token)
num=list(map(int,token))
print(num)

even=list(filter(lambda x: x%2==0,num))
print(even)

['12', '344', '566']
[12, 344, 566]
[12, 344, 566]

In [ ]:


try:
  a = 10/0
except ZeroDivisionError:
  print("you cant divide a number by 0")

print("hello world")

you cant divide a number by 0
hello world

Write a function safe_divide(a,b) that performs a/b and handles division by zero using try–except.
 Print "Division by zero" if b = 0.
Input Format:
 Two integers a b.
Output Format:
 Result or error message.
Example:
Input: 10 0  
Output: Division by zero

In [ ]:
def safe_divide(a, b):
    try:
        result = a / b
        print(result)
    except ZeroDivisionError:
        print("Division by zero")

a = int(input())
b = int(input())
safe_divide(a, b)

Division by zero

In [ ]:
#strong number calculation 
# Function to calculate factorial manually
def fac(n):
    f=1
    for i in range(1, n + 1):
        f=f*i
    return f

num = int(input())
temp = num
sum=0

while temp > 0:
    digit = temp % 10
    sum=sum+fac(digit)
    temp =temp//10

if sum == num:
    print("Strong Number")
else:
    print("Not Strong Number")

Not Strong Number

In [ ]:

string= input()

words =string.split()
print(words)
longest = words[0]
for word in words:
    if len(word) > len(longest):
        longest = word
print(longest)

['arman', 'hossain', 'arman', 'hossain']
hossain

In [ ]:

class Shape:
    def area(self):
        return 0

class Rectangle(Shape):
    def __init__(self, w, h):
        self.w = w
        self.h = h

    def area(self):
        return self.w * self.h

class Circle(Shape):
    def __init__(self, r):
        self.r = r

    def area(self):
        return 3.1416 * self.r * self.r


rect = Rectangle(5, 10)
circle = Circle(7)

print(f"Rectangle Area: {rect.area():.2f}")
print(f"Circle Area: {circle.area():.2f}")

Rectangle Area: 50.00
Circle Area: 153.94

NUMPY BASIC AND CORE  CONCEPT

#ndarry and its attributes

In [ ]:
print('hello world ')

hello world

In [ ]:
arr=[1,2,3]
print(arr*5)#list same 5 times print hobe

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
arr=[x*5 for x in arr]
print(arr)

[5, 10, 15]

In [ ]:
print(arr*5)

[5, 10, 15, 5, 10, 15, 5, 10, 15, 5, 10, 15, 5, 10, 15]

In [ ]:
#but in numpy 
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]

In [ ]:
#its a matrics 1D matrix
print(arr*5)#here it multiple the array not print as usuall five time

[ 5 10 15 20]

ndarray

1DAarry

In [ ]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]

In [ ]:
print(type(arr1))#print the dimension the array
print(arr1.ndim)#print the dimension

<class 'numpy.ndarray'>
1

2D array

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)#print 2D dimension

[[1 2 3]
 [4 5 6]]

In [ ]:
print(type(arr2))#print the dimension the array
print(arr2.ndim)#print the dimension

<class 'numpy.ndarray'>
2

In [ ]:
arr3=np.array([
    [ [1,2,3],
      [4,5,6]],
     [[4,5,6],
      [6,7,8]]
])
print(arr3)
print(type(arr3))#print the dimension the array
print(arr3.ndim)#

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [6 7 8]]]
<class 'numpy.ndarray'>
3

In [ ]:
print(arr1)
print(arr.ndim)
print(arr1.shape)
print(arr1.dtype)

[1 2 3 4 5]
1
(5,)
int64

In [ ]:
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64

In [ ]:
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.dtype)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [6 7 8]]]
3
(2, 2, 3)
int64

Nd array data type

In [ ]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64

In [ ]:
arr=np.array([1,2.3,3,4])#here a float data is then its d tpye is float
print(arr)
print(type(arr))
print(arr.dtype)

[1.  2.3 3.  4. ]
<class 'numpy.ndarray'>
float64

In [ ]:
arr=np.array([1,2.3,'3',4])#here a string is then its d tpye is string unicharecter
print(arr)
print(type(arr))
print(arr.dtype)

['1' '2.3' '3' '4']
<class 'numpy.ndarray'>
<U32

Selecting Data type for ;an array

In [ ]:
arr=np.array([1,2.3,3,4],dtype=np.int16)#also do int 32 and 64 if we want to do it than 
print(arr)
print(type(arr))
print(arr.dtype)
#int->float->string

[1 2 3 4]
<class 'numpy.ndarray'>
int16

In [ ]:
arr=np.array([1,2.3,3,300],dtype=np.int8)#here show an error because python int is 8 but we put a value is 300 thats why it show overflow
print(arr)

OverflowError: Python integer 300 out of bounds for int8

In [ ]:
arr=np.array([1,2.3,'hello',300],dtype=np.float64)#show reeon because dont convert string to float #int->float->string go only forward
print(arr)

ValueError: could not convert string to float: 'hello'

Ndarry cretion with lst existing data

In [ ]:
lst=[10,30,45,78]
print(type(lst))
arr=np.array(lst)
print(type(arr))#convert list to 1D matrix
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[10 30 45 78]

In [ ]:
lst=['hello','arman',.12,True,'ma bon nei basay']
arr=np.array(lst)
print(arr)#convertit all into string 
#int->float->string

['hello' 'arman' '0.12' 'True' 'ma bon nei basay']

tuple to numpy array

In [ ]:
tup=(10,45,78)
array=np.array(tup)
print(array)
print(array.shape)

[10 45 78]
(3,)

set as a numpy

In [ ]:
s={10,29,45}
array=np.array(s)
print(array)#it dont give us a metrix it gives us onlt  metrix

{10, 29, 45}

In [ ]:
#to solve this problem
s={10,29,45}
array=np.array(list(s))#use list method to solve this problem then it give us a matrix
print(array)
print(np.shape)

[10 29 45]
<function shape at 0x000001A19C5945E0>

Dictionay to nmpy

In [ ]:
dic={'a':10,'b':67,'c':7888}
print(dic)
keys=dic.keys()
val=dic.values()
item=dic.items()
print(keys,val,item)

{'a': 10, 'b': 67, 'c': 7888}
dict_keys(['a', 'b', 'c']) dict_values([10, 67, 7888]) dict_items([('a', 10), ('b', 67), ('c', 7888)])

In [ ]:
a=np.array(list(keys))
print(a)

['a' 'b' 'c']

In [17]:
import numpy as np
b=np.array(list(val))
print(b)

NameError: name 'val' is not defined

In [ ]:
c=np.array(list(item))
print(c)
print(type(c))

print(c.dtype)
print(c.size)

[['a' '10']
 ['b' '67']
 ['c' '7888']]
<class 'numpy.ndarray'>
<U21
6

Nd array create with scratch

In [ ]:
arr=np.random.randint(1,10,size=(3,3))
print(arr)

[[7 6 6]
 [5 5 4]
 [1 7 5]]

np  Zeros

In [ ]:
arr=np.zeros((1,3))#all values remain free
print(arr)

[[0. 0. 0.]]

In [ ]:
arr=np.zeros((3,3),dtype=np.int32)#all value are zero 

print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

In [ ]:
#existing array to crete an matrix arr ager matrix
arr=np.zeros_like(arr)
print(arr)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]

In [ ]:
import numpy as np
ar=np.ones([5,5])
print(ar)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [ ]:
ar=np.ones_like(arr2)
print(ar)

[[1 1 1]
 [1 1 1]]

In [ ]:
#n.empty
arr=np.empty([4,4])
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.33511290e-306]
 [6.23058368e-307 2.22522597e-306 1.33511969e-306 1.37962320e-306]
 [9.34604358e-307 9.79101082e-307 1.78020576e-306 1.69119873e-306]
 [2.22522868e-306 1.24611809e-306 8.06632139e-308 1.60221208e-306]]

In [ ]:
arr=np.empty_like(arr2)
print(arr)

[[1 1 1]
 [1 1 1]]

np.full

In [ ]:
arr=np.full((4,3),10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]

In [ ]:
arr=np.full_like(arr2,12)
print(arr)

[[12 12 12]
 [12 12 12]]

Array generation with rsndom vlue

In [ ]:
arr=np.random.randint(1,10,(4,4))#first range give random value in this rnge 2nd shape
print(arr)

[[6 3 8 1]
 [2 6 9 6]
 [2 9 9 2]
 [7 6 2 9]]

In [ ]:

a=np.random.rand(2,3)#rand in float data is given always 
a

array([[0.49887936, 0.30507716, 0.22137317],
       [0.53651685, 0.37101371, 0.41189358]])

In [ ]:
aa=np.random.randint(1,10,(4,4))
print(aa)

[[9 3 5 5]
 [6 5 4 3]
 [8 6 9 9]
 [8 1 7 1]]

In [ ]:
#give randomly floating values 
aa=np.random.uniform(1,89,(2,2))
print(aa)

[[23.53740928  2.66136224]
 [71.41182193 13.68084871]]

nd_array generation with arange

In [ ]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.arange(1,10,2).reshape(3,3)
arr

ValueError: cannot reshape array of size 5 into shape (3,3)

In [ ]:
arr = np.arange(1, 10, 2).reshape(5, 1)
print(arr)

[[1]
 [3]
 [5]
 [7]
 [9]]

In [ ]:
#np.linepace\\

arr=np.linspace(1,10,11)
print(arr)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]

In [ ]:
#np.logspace
arr=np.logspace(0,4,5)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]

matrix for linear algebra

In [ ]:
#diagonal matrix
dia_matrix=np.diag([1,2,3])
print(dia_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]

In [ ]:
#diagonal matrix
dia_matrix=np.diag([1,2])
print(dia_matrix)

[[1 0]
 [0 2]]

Indentity matrix

In [ ]:
I_mat=np.eye(3)
print(I_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
arr=np.eye(3,4,-1)

arr

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

#indexcing nad slicing in a 1D and @D array

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
arr[2]=100
arr

array([  1,   2, 100,   4,   5])

In [3]:
a2=np.array([
    [1,2,3],
    [4,5,6]
])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a2[0,1]=100
a2

array([[  1, 100,   3],
       [  4,   5,   6]])

Slicing !D array=[start,end-1,step]

In [6]:
arr

array([  1,   2, 100,   4,   5])

In [12]:
arr[2:4]

array([100,   4])

2D array slicing array[row_start:row_end,column_start:column_end,step]

alaways end=end-1

In [13]:
a2

array([[  1, 100,   3],
       [  4,   5,   6]])

In [ ]:
a2[0:1,]#row start 0 no and and row end 1 means 1-1=0 no rows which is first row

array([[  1, 100,   3]])

In [16]:
a2

array([[  1, 100,   3],
       [  4,   5,   6]])

In [17]:
a=np.random.randint(1,10,size=(3,3))
a

array([[2, 8, 3],
       [5, 8, 6],
       [9, 7, 7]], dtype=int32)

In [18]:
a[1:2,]

array([[5, 8, 6]], dtype=int32)

In [21]:
a[1:2,1:2]

array([[8]], dtype=int32)

In [22]:
a[2:2,1:2]

array([], shape=(0, 1), dtype=int32)

In [24]:
b=np.random.randint(1,10,size=(4,4))
b

array([[2, 4, 5, 7],
       [4, 2, 5, 3],
       [8, 1, 6, 6],
       [7, 3, 3, 2]], dtype=int32)

In [29]:
b[1:5,2:4]

array([[5, 3],
       [6, 6],
       [3, 2]], dtype=int32)

In [30]:
b

array([[2, 4, 5, 7],
       [4, 2, 5, 3],
       [8, 1, 6, 6],
       [7, 3, 3, 2]], dtype=int32)

In [ ]:
b[::,3,]#gime me column but in vertically

array([7, 3, 6, 2], dtype=int32)

In [32]:
b

array([[2, 4, 5, 7],
       [4, 2, 5, 3],
       [8, 1, 6, 6],
       [7, 3, 3, 2]], dtype=int32)

In [34]:
b[::,1:1]
b[::,1:4]

array([[4, 5, 7],
       [2, 5, 3],
       [1, 6, 6],
       [3, 3, 2]], dtype=int32)

advanced indexicing

In [35]:
b

array([[2, 4, 5, 7],
       [4, 2, 5, 3],
       [8, 1, 6, 6],
       [7, 3, 3, 2]], dtype=int32)

In [36]:
value=b[[2,3]]
value

array([[8, 1, 6, 6],
       [7, 3, 3, 2]], dtype=int32)

In [38]:
b

array([[2, 4, 5, 7],
       [4, 2, 5, 3],
       [8, 1, 6, 6],
       [7, 3, 3, 2]], dtype=int32)

In [41]:
value=b[[1,1]]
value

array([[4, 2, 5, 3],
       [4, 2, 5, 3]], dtype=int32)

In [42]:
b[b>5]

array([7, 8, 6, 6, 7], dtype=int32)

Itereation on matrix

In [43]:
a=[[10,20,30],[40,60,70]]
a

[[10, 20, 30], [40, 60, 70]]

In [45]:
arr=np.array(a)
arr

array([[10, 20, 30],
       [40, 60, 70]])

In [51]:
for i in arr:
    print(i)

[10 20 30]
[40 60 70]

In [52]:
for i in np.nditer(arr):
    print(i)

10
20
30
40
60
70

nDarrya manipulation

In [55]:
array=np.random.randint(1,100,size=(10,5))
array

array([[67, 39, 90, 40, 27],
       [73, 39, 67, 59, 69],
       [86, 53, 62, 26, 53],
       [82, 11, 59, 48,  3],
       [10, 16, 18, 94, 26],
       [ 4, 30, 78, 60, 59],
       [91, 35, 63, 68, 53],
       [46, 63, 50, 25, 81],
       [68,  3, 65,  1, 24],
       [70, 33,  9, 17, 35]], dtype=int32)

In [58]:
array.shape

(10, 5)

2d array convert in 1D array

In [60]:
flatter=array.flatten()
flatter

array([67, 39, 90, 40, 27, 73, 39, 67, 59, 69, 86, 53, 62, 26, 53, 82, 11,
       59, 48,  3, 10, 16, 18, 94, 26,  4, 30, 78, 60, 59, 91, 35, 63, 68,
       53, 46, 63, 50, 25, 81, 68,  3, 65,  1, 24, 70, 33,  9, 17, 35],
      dtype=int32)

In [ ]:
#row wise flateen
row_wise_flatten=np.ravel(array,order='c')#here when we put in here 'c' it print col_wise value
row_wise_flatten

array([67, 39, 90, 40, 27, 73, 39, 67, 59, 69, 86, 53, 62, 26, 53, 82, 11,
       59, 48,  3, 10, 16, 18, 94, 26,  4, 30, 78, 60, 59, 91, 35, 63, 68,
       53, 46, 63, 50, 25, 81, 68,  3, 65,  1, 24, 70, 33,  9, 17, 35],
      dtype=int32)

In [62]:
array

array([[67, 39, 90, 40, 27],
       [73, 39, 67, 59, 69],
       [86, 53, 62, 26, 53],
       [82, 11, 59, 48,  3],
       [10, 16, 18, 94, 26],
       [ 4, 30, 78, 60, 59],
       [91, 35, 63, 68, 53],
       [46, 63, 50, 25, 81],
       [68,  3, 65,  1, 24],
       [70, 33,  9, 17, 35]], dtype=int32)

In [ ]:
b=array.reshape(25,2)#totall value milte hobe 
b

array([[67, 39],
       [90, 40],
       [27, 73],
       [39, 67],
       [59, 69],
       [86, 53],
       [62, 26],
       [53, 82],
       [11, 59],
       [48,  3],
       [10, 16],
       [18, 94],
       [26,  4],
       [30, 78],
       [60, 59],
       [91, 35],
       [63, 68],
       [53, 46],
       [63, 50],
       [25, 81],
       [68,  3],
       [65,  1],
       [24, 70],
       [33,  9],
       [17, 35]], dtype=int32)

In [65]:
array

array([[67, 39, 90, 40, 27],
       [73, 39, 67, 59, 69],
       [86, 53, 62, 26, 53],
       [82, 11, 59, 48,  3],
       [10, 16, 18, 94, 26],
       [ 4, 30, 78, 60, 59],
       [91, 35, 63, 68, 53],
       [46, 63, 50, 25, 81],
       [68,  3, 65,  1, 24],
       [70, 33,  9, 17, 35]], dtype=int32)

In [66]:
col_wise_flatten=np.ravel(array,order='c')#here when we put in here 'c' it print col_wise value
col_wise_flatten

array([67, 39, 90, 40, 27, 73, 39, 67, 59, 69, 86, 53, 62, 26, 53, 82, 11,
       59, 48,  3, 10, 16, 18, 94, 26,  4, 30, 78, 60, 59, 91, 35, 63, 68,
       53, 46, 63, 50, 25, 81, 68,  3, 65,  1, 24, 70, 33,  9, 17, 35],
      dtype=int32)

In [69]:
#concatanatio of 2 array
a=np.random.randint(1,5,size=(3,3))
a

array([[1, 1, 2],
       [3, 1, 4],
       [4, 1, 4]], dtype=int32)

In [70]:
b=np.random.randint(1,5,size=(3,3))
b

array([[2, 1, 2],
       [2, 1, 3],
       [2, 3, 3]], dtype=int32)

In [ ]:
con_=np.concatenate((a,b))#merge of 2 array not sun or anythings alltime 2 marics in equall
con_

array([[1, 1, 2],
       [3, 1, 4],
       [4, 1, 4],
       [2, 1, 2],
       [2, 1, 3],
       [2, 3, 3]], dtype=int32)

In [72]:
a

array([[1, 1, 2],
       [3, 1, 4],
       [4, 1, 4]], dtype=int32)

In [ ]:
transpose=a.T#row is turn column and column turns row
transpose

array([[1, 3, 4],
       [1, 1, 1],
       [2, 4, 4]], dtype=int32)

split array

In [81]:
sin=np.sin(a)
sin

array([[[ 0.84147098,  0.84147098,  0.90929743]],

       [[ 0.14112001,  0.84147098, -0.7568025 ]],

       [[-0.7568025 ,  0.84147098, -0.7568025 ]]])

In [82]:
#radian to degree
dig=np.rad2deg(a)
dig

array([[[ 57.29577951,  57.29577951, 114.59155903]],

       [[171.88733854,  57.29577951, 229.18311805]],

       [[229.18311805,  57.29577951, 229.18311805]]])

In [83]:
base=np.log10(a)
base

array([[[0.        , 0.        , 0.30103   ]],

       [[0.47712125, 0.        , 0.60205999]],

       [[0.60205999, 0.        , 0.60205999]]])

In [84]:
aa=np.sqrt(a)
aa

array([[[1.        , 1.        , 1.41421356]],

       [[1.73205081, 1.        , 2.        ]],

       [[2.        , 1.        , 2.        ]]])

In [85]:
#numpy boardcasting
x=np.array([10,2,3,4,5])
x

array([10,  2,  3,  4,  5])

In [86]:
res=x**2
res

array([100,   4,   9,  16,  25])

In [87]:
mat=np.array([
    [10,20,30],
    [40,50,60]
])
mat

array([[10, 20, 30],
       [40, 50, 60]])

In [88]:
res=mat+2
res

array([[12, 22, 32],
       [42, 52, 62]])

In [89]:
#arithmatis operation as usall 
x=np.random.randint(1,5,size=(2,2))
y=np.random.randint(1,5,size=(2,2))
print(x+y)

[[2 4]
 [8 8]]

In [91]:
x

array([[1, 1],
       [4, 4]], dtype=int32)

In [92]:
y

array([[1, 3],
       [4, 4]], dtype=int32)

In [90]:
#logical function
gretter_than=x>y
gretter_than

array([[False, False],
       [False, False]])

In [93]:
equall=x==y
equall

array([[ True, False],
       [ True,  True]])

In [94]:
#all
gretter_than=x>y
print(np.all(gretter_than))

False

In [ ]:
print(np.any(equall))#kono akta true hole tobei true show korbe

True

In [96]:
#sorting
x

array([[1, 1],
       [4, 4]], dtype=int32)

In [97]:
#inplace sorting
z=x.copy()
z

array([[1, 1],
       [4, 4]], dtype=int32)

In [99]:
z.sort()
z

array([[1, 1],
       [4, 4]], dtype=int32)

In [100]:
#copy sorting
sort=np.sort(x)
sort

array([[1, 1],
       [4, 4]], dtype=int32)

In [101]:
x

array([[1, 1],
       [4, 4]], dtype=int32)


1 . Create a 1D, 2D, and 3D NumPy array and print their 

dimensions and shapes.

In [103]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [104]:
print(a.ndim)

1

In [105]:
print(a.shape)

(5,)

In [106]:
b=np.array([
    [1,2,3,4,5],
    [1,2,3,4,5]
])
b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [107]:
print(b.ndim)

2

In [108]:
print(b.shape)

(2, 5)

In [109]:
c=np.array([
        [[1,2,3,4,5],
        [1,2,3,4,5]],
        [[1,2,3,4,5],
        [1,2,3,4,5]]
])
c

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [111]:
print(c.shape)
print(c.ndim)

(2, 2, 5)
3

. Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7

In [113]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
b=np.ones((2,5))
b
print(b.dtype)

float64

In [116]:
a=np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [119]:
lst=[x  for x in range(10,52,2)]
lst
array=np.array(lst)
array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [120]:
arr=np.random.randint(0,15,size=(4,4))
arr

array([[ 7,  6,  7, 10],
       [14, 13,  5, 10],
       [14,  7,  0, 12],
       [ 3,  7,  8,  7]], dtype=int32)

In [122]:
arr[0:1,]

array([[ 7,  6,  7, 10]], dtype=int32)

In [128]:
#last column
arr[::,3:4]

array([[10],
       [10],
       [12],
       [ 7]], dtype=int32)

In [129]:
arr

array([[ 7,  6,  7, 10],
       [14, 13,  5, 10],
       [14,  7,  0, 12],
       [ 3,  7,  8,  7]], dtype=int32)

In [131]:
arr[1:3,1:3]

array([[13,  5],
       [ 7,  0]], dtype=int32)

In [132]:
a=np.random.randint(1,5,size=(3,3))
a

array([[1, 3, 4],
       [4, 2, 4],
       [1, 4, 1]], dtype=int32)

In [133]:
one_D=np.array([1,2,3])
one_D

array([1, 2, 3])

In [134]:
add=a+one_D
add

array([[2, 5, 7],
       [5, 4, 7],
       [2, 6, 4]])

In [135]:
a

array([[1, 3, 4],
       [4, 2, 4],
       [1, 4, 1]], dtype=int32)

In [136]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [137]:
arr

array([[ 7,  6,  7, 10],
       [14, 13,  5, 10],
       [14,  7,  0, 12],
       [ 3,  7,  8,  7]], dtype=int32)

In [138]:
y

array([[1, 3],
       [4, 4]], dtype=int32)

In [139]:
x

array([[1, 1],
       [4, 4]], dtype=int32)

In [140]:
x+y/2

array([[1.5, 2.5],
       [6. , 6. ]])

In [1]:
x**2 + y**2

NameError: name 'x' is not defined

In [1]:
import numpy as np

In [1]:
import numpy as np 
import pandas as pd

import numpy as np

import pandas as pd

In [1]:
import numpy as np
import pandas as pd

In [9]:
data={
      'name':["arman","hossain","shawon",'bob'],
      "city":['new work','dhaka','uk','uk'],
      'department':["HR",'IT',"HR",'ml'],
       "salary":[1000,200,3000,2000]
}
df=pd.DataFrame(data)
df

      name      city department  salary
0    arman  new work         HR    1000
1  hossain     dhaka         IT     200
2   shawon        uk         HR    3000
3      bob        uk         ml    2000

In [14]:
#here only print where city include only DHA word
df.loc[df['city'].str.contains('dha')]#when we inter"Dha "" its return error because its a case sensitive

      name   city department  salary
1  hossain  dhaka         IT     200

In [6]:
#To remove case sensitive we can apply
df.loc[df['city'].str.contains('Dha',case=False)]#now its dont show any error

      name   city department  salary
1  hossain  dhaka         IT     200

In [15]:
# here only print whose city name is start with dha 
df.loc [df['city'].str.contains(r'uk')]

     name city department  salary
2  shawon   uk         HR    3000
3     bob   uk         ml    2000

In [16]:
df.loc [df['city'].str.contains(r'^uk')]

     name city department  salary
2  shawon   uk         HR    3000
3     bob   uk         ml    2000

In [17]:
#ends with specific charecter 
df.loc [df['city'].str.contains(r'uk$')]

     name city department  salary
2  shawon   uk         HR    3000
3     bob   uk         ml    2000

In [18]:
#start with vowel
df.loc[df['name'].str.contains(r"^[aeiou]")]

    name      city department  salary
0  arman  new work         HR    1000

In [19]:
# jader nam a d and k ase tader kei print korbe shudu  je sob shohorer
df.loc [df['city'].str.contains(r'dh|k')]

      name      city department  salary
0    arman  new work         HR    1000
1  hossain     dhaka         IT     200
2   shawon        uk         HR    3000
3      bob        uk         ml    2000

In [20]:
df.loc [df['city'].str.contains(r'new|ka')]

      name      city department  salary
0    arman  new work         HR    1000
1  hossain     dhaka         IT     200

In [ ]:
df['country']='bangladesh'# new country add hobe sob value thakbe bangladesh
df

      name      city department  salary     country
0    arman  new work         HR    1000  bangladesh
1  hossain     dhaka         IT     200  bangladesh
2   shawon        uk         HR    3000  bangladesh
3      bob        uk         ml    2000  bangladesh

In [23]:
df=pd.read_csv("student.csv")
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0

In [24]:
df['country']='bangladesh'
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,country
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,bangladesh
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,bangladesh
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,bangladesh
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,bangladesh
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,bangladesh
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,bangladesh
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,bangladesh
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,bangladesh
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,bangladesh
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,bangladesh
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,bangladesh
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,bangladesh
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,bangladesh
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,bangladesh
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,bangladesh
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,bangladesh
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,bangladesh
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh

In [ ]:
df["totall_mark"]=df['Math_Mark']+df['Biology_Mark']+df['Physics_Mark']#in this now create a totall  mark column where i put the all mark sum 
#then where a single mark is nan if any student then show the totall mark is nan for this student
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,country,totall_mark
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh,NaN
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,bangladesh,150.0
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,bangladesh,194.0
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,bangladesh,NaN
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,bangladesh,159.0
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,bangladesh,NaN
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,bangladesh,229.0
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,bangladesh,231.0
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,bangladesh,NaN
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,bangladesh,NaN
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,bangladesh,NaN
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,bangladesh,191.0
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,bangladesh,213.0
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,bangladesh,NaN
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,bangladesh,NaN
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh,174.0
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,bangladesh,241.0
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh,191.0
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,bangladesh,220.0
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,bangladesh,211.0
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh,NaN
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh,191.0
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh,174.0

In [27]:
#we know that if we want in a condition then we put numpy command then apply the condition 
#in this where mark is gretter than 90 give them A+ if not 90 up then give them A and you put this all of things in a new column 
df['A+ in math']=np.where(df['Math_Mark']>90,'A+','A')
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,country,totall_mark,A+ in math
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh,NaN,A
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,bangladesh,150.0,A
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,bangladesh,194.0,A
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,bangladesh,NaN,A
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,bangladesh,159.0,A
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,bangladesh,NaN,A
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,bangladesh,229.0,A
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,bangladesh,231.0,A
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,bangladesh,NaN,A
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,bangladesh,NaN,A+
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,bangladesh,NaN,A
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,bangladesh,191.0,A
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,bangladesh,213.0,A
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,bangladesh,NaN,A+
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,bangladesh,NaN,A+
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh,174.0,A
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,bangladesh,241.0,A
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh,191.0,A
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,bangladesh,220.0,A
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,bangladesh,211.0,A
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh,NaN,A
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh,191.0,A
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh,174.0,A

In [28]:
df["Passed_In_Bio"]=df['Biology_Mark']>70
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,country,totall_mark,A+ in math,Passed_In_Bio
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh,NaN,A,False
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,bangladesh,150.0,A,False
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,bangladesh,194.0,A,False
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,bangladesh,NaN,A,True
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,bangladesh,159.0,A,False
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,bangladesh,NaN,A,False
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,bangladesh,229.0,A,False
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,bangladesh,231.0,A,True
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,bangladesh,NaN,A,False
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,bangladesh,NaN,A+,False
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,bangladesh,NaN,A,False
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,bangladesh,191.0,A,False
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,bangladesh,213.0,A,True
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,bangladesh,NaN,A+,False
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,bangladesh,NaN,A+,True
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh,174.0,A,False
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,bangladesh,241.0,A,False
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh,191.0,A,True
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,bangladesh,220.0,A,False
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,bangladesh,211.0,A,True
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,bangladesh,NaN,A,False
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,bangladesh,191.0,A,True
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,bangladesh,174.0,A,False

In [38]:
df=df.drop('country',axis=1)
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False

In [ ]:
#Unique and null cheacking
df['StudentName'].unique()#show all unique values

array(['Nusrat Hossain', 'Nusrat Bhuiyan', 'Tania Sarkar', 'Rana Bhuiyan',
       'Arman Rahman', 'Fahim Khan', 'Joy Roy', 'Nusrat Ahmed',
       'Mona Chowdhury', 'Kamal Islam', 'Sabrina Hasan', 'Sabrina Khan',
       'Tanvir Ahmed', 'Fahim Hossain', 'Rana Hasan', 'Samir Sarkar',
       'Rashed Ahmed', 'Tania Hossain', 'Nabila Roy'], dtype=object)

In [ ]:
#number of unique values 
len(df['StudentName'].unique())# here show the number of unique value

19

In [ ]:
#now we separate the student name as usall
df['First_name']=df['StudentName'].str.split(' ').str[0]
df# now we can see the separate the first name of a student

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [ ]:
#here we now apply this condition or work in this csv file it dont save the csv file 
#if we want to save this all in csv file then apply this command
df.to_csv('student.csv')# now create the new csv fie

In [ ]:
#cheack the all null values in  pandas csv 
df.isnull()#if there is a an  show true than every

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,False,False,False,True,False,False,True,True,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,True,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,True,False,True,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,True,False,True,False,True,True,False,False
9,False,False,False,False,False,True,False,True,False,False
10,False,False,False,False,True,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,True,False,True,False,False
14,False,False,False,False,False,False,True,True,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,True,False,False,False,False,False,False,False
17,False,False,True,True,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,True,False,False,True,True,False,False
21,False,False,True,True,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False

In [ ]:
df['Biology_Mark'].isnull()#null pele true return korbe ta na hole false return jorbe

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
Name: Biology_Mark, dtype: bool

In [52]:
df['Biology_Mark'].isnull().sum()

np.int64(3)

In [ ]:
df['Biology_Mark'].notnull()#null pele false return korbe

0      True
1      True
2      True
3      True
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11     True
12     True
13    False
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
Name: Biology_Mark, dtype: bool

In [ ]:
#overall column a null ase kina ta check korboo amra 
df['Biology_Mark'].hasnans#true tarmane ai column a a null value ase

True

#Handeling duplicate in Data frame

In [51]:
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [ ]:
df.duplicated()#akta row  dui tin bar thakle true return korbe tarmane oi row ta ase aro dui tinbar 20,21,22 rown aro ase

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22     True
dtype: bool

In [53]:
df.duplicated().sum()

np.int64(3)

In [ ]:
df.drop_duplicates()# here we drop the duplicate

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila

In [55]:
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [ ]:
df.drop_duplicates(subset=['District'])#aikhan a column a joto duplicate ase sob remove kore dibe

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina

In [ ]:
df.drop_duplicates(subset=['District'],keep='last')
#👉 এখানে বলা হচ্ছে, “ডুপ্লিকেট পাওয়া গেলে শেষেরটি রাখবে, আগেরগুলো বাদ দেবে।”
#অর্থাৎ, একই District নাম একাধিকবার থাকলে, সেই District-এর শেষ occurrence টা থাকবে, বাকিগুলো ডিলিট হয়ে যাবে।first dile first ar ta thakbe

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

HANDELING NULL VALUES

In [ ]:
df.dropna()#nan value thakle sei row e delete kore dibe 1 ta nan value thaklei delete kore dile

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [63]:
#jodi kono row a sob gulai nan value theke thahole full row tai delete kore dibe 
df.dropna(how='all')

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [ ]:
df.dropna(how='any')#null thaklei delete kore dibe

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [65]:
#column wise kono column a null pele pura column delete kore dibe 
df.dropna(subset=['Math_Mark'])

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [66]:
df

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [67]:
#null gula 0 diye fillup kore felbe 
df.fillna(0)

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,0,54.0,48.0,0.0,0.0,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,0,0.0,77.0,57.0,0.0,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,0.0,94.0,0.0,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,0,Dr. Siddique,0.0,42.0,0.0,0.0,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,0.0,64.0,0.0,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,0.0,62.0,53.0,0.0,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,0.0,65.0,0.0,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,0.0,0.0,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,0,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,0,0,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,0,54.0,48.0,0.0,0.0,False,Nusrat
21,S018,Rashed Ahmed,0,0,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [68]:
df.fillna('unknown')

,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,S001,Nusrat Hossain,Sylhet,unknown,54.0,48.0,unknown,unknown,False,Nusrat
1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,S004,Rana Bhuiyan,Rangpur,unknown,unknown,77.0,57.0,unknown,True,Rana
4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,unknown,94.0,unknown,False,Fahim
6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,S009,Mona Chowdhury,unknown,Dr. Siddique,unknown,42.0,unknown,unknown,False,Mona
9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,unknown,64.0,unknown,False,Kamal
10,S011,Sabrina Hasan,Barishal,Mr. Karim,unknown,62.0,53.0,unknown,False,Sabrina
11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,unknown,65.0,unknown,False,Fahim
14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,unknown,unknown,True,Sabrina
15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,S017,Samir Sarkar,unknown,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,S018,Rashed Ahmed,unknown,unknown,48.0,72.0,71.0,191.0,True,Rashed
18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,S001,Nusrat Hossain,Sylhet,unknown,54.0,48.0,unknown,unknown,False,Nusrat
21,S018,Rashed Ahmed,unknown,unknown,48.0,72.0,71.0,191.0,True,Rashed
22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [70]:
df['Math_Mark'].fillna('unkown')

0       54.0
1       67.0
2       78.0
3     unkown
4       57.0
5       46.0
6       86.0
7       58.0
8     unkown
9       95.0
10    unkown
11      86.0
12      84.0
13      91.0
14      96.0
15      69.0
16      77.0
17      48.0
18      80.0
19      64.0
20      54.0
21      48.0
22      69.0
Name: Math_Mark, dtype: object

In [71]:
#math mark ar nan value gula totall math mark ar mean diye fill hoye jabe 
df['Math_Mark'].fillna(df['Math_Mark'].mean())

0     54.00
1     67.00
2     78.00
3     70.35
4     57.00
5     46.00
6     86.00
7     58.00
8     70.35
9     95.00
10    70.35
11    86.00
12    84.00
13    91.00
14    96.00
15    69.00
16    77.00
17    48.00
18    80.00
19    64.00
20    54.00
21    48.00
22    69.00
Name: Math_Mark, dtype: float64

In [ ]:
df['Math_Mark'].mean()

np.float64(70.35)

SAME THINGS CAN DO

#.sum,min(),max(),mean(),median(),mode(),std()

In [73]:
#corelation metrics
df[['Math_Mark','Biology_Mark']].corr()

              Math_Mark  Biology_Mark
Math_Mark       1.00000       0.08298
Biology_Mark    0.08298       1.00000

In [ ]:
#row wise amra mark ar value gula sum korbooo
df.[['Math_Mark','Biology_Mark']].sum(axis=1)

In [75]:
df[['Math_Mark', 'Biology_Mark']].sum(axis=1)

0     102.0
1     109.0
2     119.0
3      77.0
4     106.0
5      46.0
6     155.0
7     151.0
8      42.0
9      95.0
10     62.0
11    141.0
12    159.0
13     91.0
14    181.0
15    118.0
16    144.0
17    120.0
18    130.0
19    142.0
20    102.0
21    120.0
22    118.0
dtype: float64

In [5]:
import numpy as np
import pandas as pd

In [15]:
df=pd.read_csv("student.csv")
df

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [ ]:
df['Totall_M_B']=df[['Math_Mark','Biology_Mark']].sum(axis=1)#aikhan a math and bio mark sum hoye notun akta column a bosbe
#column r nam holo [Totall_M_B]
df

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name,Totall_M_B
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat,109.0
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania,119.0
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana,77.0
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman,106.0
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim,46.0
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy,155.0
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat,151.0
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona,42.0
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal,95.0
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina,62.0
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina,141.0
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir,159.0
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim,91.0
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina,181.0
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,118.0
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir,144.0
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,120.0
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania,130.0
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila,142.0
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,120.0
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,118.0

In [ ]:
#akhn jodi 100 ta column thake sob gular nam likhe amne sum kora onk kosto kor tai amr iloc use kore sob column nibo
df['Totall_']=df.iloc[::,5:8].sum(axis=1)#math bio and phy  totall of this mark as usall
df

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name,Totall_
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat,150.0
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania,194.0
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana,134.0
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman,159.0
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim,140.0
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy,229.0
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat,231.0
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona,42.0
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal,159.0
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina,115.0
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina,191.0
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir,213.0
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim,156.0
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina,181.0
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,174.0
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir,241.0
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,191.0
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania,220.0
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila,211.0
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,191.0
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,174.0

In [27]:
#min and max scaling
mn=df["totall_mark"].min()#minimun num sob coumn ar mark ar modde 
mn

np.float64(150.0)

In [28]:
mx=df["totall_mark"].max()#maximum mark show korbe 
mx

np.float64(241.0)

In [30]:
df['scaled_mark']=df['totall_mark'].apply(lambda x:(x-mn)/(mx-mn))
df

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name,Totall_,scaled_mark
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0,NaN
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat,150.0,0.000000
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania,194.0,0.483516
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana,134.0,NaN
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman,159.0,0.098901
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim,140.0,NaN
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy,229.0,0.868132
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat,231.0,0.890110
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona,42.0,NaN
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal,159.0,NaN
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina,115.0,NaN
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina,191.0,0.450549
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir,213.0,0.692308
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim,156.0,NaN
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina,181.0,NaN
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,174.0,0.263736
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir,241.0,1.000000
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,191.0,0.450549
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania,220.0,0.769231
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila,211.0,0.670330
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0,NaN
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,191.0,0.450549
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,174.0,0.263736

In [ ]:
df.drop("Passed_In_Bio", axis=1)

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,First_name,Totall_,scaled_mark
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,Nusrat,102.0,NaN
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,Nusrat,150.0,0.000000
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,Tania,194.0,0.483516
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,Rana,134.0,NaN
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,Arman,159.0,0.098901
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,Fahim,140.0,NaN
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,Joy,229.0,0.868132
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,Nusrat,231.0,0.890110
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,Mona,42.0,NaN
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,Kamal,159.0,NaN
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,Sabrina,115.0,NaN
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,Sabrina,191.0,0.450549
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,Tanvir,213.0,0.692308
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,Fahim,156.0,NaN
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,Sabrina,181.0,NaN
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,Rana,174.0,0.263736
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,Samir,241.0,1.000000
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,Rashed,191.0,0.450549
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,Tania,220.0,0.769231
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,Nabila,211.0,0.670330
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,Nusrat,102.0,NaN
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,Rashed,191.0,0.450549
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,Rana,174.0,0.263736

In [43]:
def grade(marks):
    if marks >= 220:
        return 'A+'
    elif marks >= 200:
        return 'A'
    else:
        return 'A-'

df['Grade'] = df['totall_mark'].apply(grade)
df

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name,Totall_,scaled_mark,Grade
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0,NaN,A-
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat,150.0,0.000000,A-
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania,194.0,0.483516,A-
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana,134.0,NaN,A-
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman,159.0,0.098901,A-
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim,140.0,NaN,A-
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy,229.0,0.868132,A+
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat,231.0,0.890110,A+
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona,42.0,NaN,A-
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal,159.0,NaN,A-
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina,115.0,NaN,A-
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina,191.0,0.450549,A-
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir,213.0,0.692308,A
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim,156.0,NaN,A-
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina,181.0,NaN,A-
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,174.0,0.263736,A-
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir,241.0,1.000000,A+
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,191.0,0.450549,A-
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania,220.0,0.769231,A+
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila,211.0,0.670330,A
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat,102.0,NaN,A-
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed,191.0,0.450549,A-
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana,174.0,0.263736,A-

In [44]:
data=pd.read_csv("student.csv")
data

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [71]:
import pandas as pd

data = {
    'ID': [1, 2, 3, 4],
    'FullName': ['karima', 'Meem', 'Yeanty', 'Khadiza'],
    'EnrollmentDate': ['2024-09-01', '2024-10-02', '2025-06-03', '2024-04-04'],
    'FinishDate': ['2025-10-09', '2025-10-10', '2025-10-11', '2025-10-12']
}

df = pd.DataFrame(data)
print(df)

   ID FullName EnrollmentDate  FinishDate
0   1   karima     2024-09-01  2025-10-09
1   2     Meem     2024-10-02  2025-10-10
2   3   Yeanty     2025-06-03  2025-10-11
3   4  Khadiza     2024-04-04  2025-10-12

In [72]:
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])
df['FinishDate'] = pd.to_datetime(df['FinishDate'])

In [73]:
df['Enroll_Year']=df['EnrollmentDate'].dt.year
df

   ID FullName EnrollmentDate FinishDate  Enroll_Year
0   1   karima     2024-09-01 2025-10-09         2024
1   2     Meem     2024-10-02 2025-10-10         2024
2   3   Yeanty     2025-06-03 2025-10-11         2025
3   4  Khadiza     2024-04-04 2025-10-12         2024

In [74]:
df['Enroll_Month']=df['EnrollmentDate'].dt.month
df

   ID FullName EnrollmentDate FinishDate  Enroll_Year  Enroll_Month
0   1   karima     2024-09-01 2025-10-09         2024             9
1   2     Meem     2024-10-02 2025-10-10         2024            10
2   3   Yeanty     2025-06-03 2025-10-11         2025             6
3   4  Khadiza     2024-04-04 2025-10-12         2024             4

In [76]:
df['Enroll_Day']=df['EnrollmentDate'].dt.day
df

,ID,FullName,EnrollmentDate,FinishDate,Enroll_Year,Enroll_Month,Enroll_Day
0,1,karima,2024-09-01,2025-10-09,2024,9,1
1,2,Meem,2024-10-02,2025-10-10,2024,10,2
2,3,Yeanty,2025-06-03,2025-10-11,2025,6,3
3,4,Khadiza,2024-04-04,2025-10-12,2024,4,4

In [77]:
df['FinishYear']=df['FinishDate'].dt.year
df

,ID,FullName,EnrollmentDate,FinishDate,Enroll_Year,Enroll_Month,Enroll_Day,FinishYear
0,1,karima,2024-09-01,2025-10-09,2024,9,1,2025
1,2,Meem,2024-10-02,2025-10-10,2024,10,2,2025
2,3,Yeanty,2025-06-03,2025-10-11,2025,6,3,2025
3,4,Khadiza,2024-04-04,2025-10-12,2024,4,4,2025

In [78]:
df['FinishMonth']=df['FinishDate'].dt.month
df

,ID,FullName,EnrollmentDate,FinishDate,Enroll_Year,Enroll_Month,Enroll_Day,FinishYear,FinishMonth
0,1,karima,2024-09-01,2025-10-09,2024,9,1,2025,10
1,2,Meem,2024-10-02,2025-10-10,2024,10,2,2025,10
2,3,Yeanty,2025-06-03,2025-10-11,2025,6,3,2025,10
3,4,Khadiza,2024-04-04,2025-10-12,2024,4,4,2025,10

In [79]:
df['Finishday']=df['FinishDate'].dt.day
df

,ID,FullName,EnrollmentDate,FinishDate,Enroll_Year,Enroll_Month,Enroll_Day,FinishYear,FinishMonth,Finishday
0,1,karima,2024-09-01,2025-10-09,2024,9,1,2025,10,9
1,2,Meem,2024-10-02,2025-10-10,2024,10,2,2025,10,10
2,3,Yeanty,2025-06-03,2025-10-11,2025,6,3,2025,10,11
3,4,Khadiza,2024-04-04,2025-10-12,2024,4,4,2025,10,12

In [ ]:
df['Totall_Time_Taken']=df["FinishDate"]-df['EnrollmentDate']#enrollment and finist day ar maje koto din ta show korbe
df

,ID,FullName,EnrollmentDate,FinishDate,Enroll_Year,Enroll_Month,Enroll_Day,FinishYear,FinishMonth,Finishday,Totall_Time_Taken
0,1,karima,2024-09-01,2025-10-09,2024,9,1,2025,10,9,403 days
1,2,Meem,2024-10-02,2025-10-10,2024,10,2,2025,10,10,373 days
2,3,Yeanty,2025-06-03,2025-10-11,2025,6,3,2025,10,11,130 days
3,4,Khadiza,2024-04-04,2025-10-12,2024,4,4,2025,10,12,556 days

GROUP BY IN PANDAS

In [81]:
data=pd.read_csv("student.csv")
data

,Unnamed: 0,ID,StudentName,District,Instructor,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
0,0,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
1,1,S002,Nusrat Bhuiyan,Chattogram,Dr. Siddique,67.0,42.0,41.0,150.0,False,Nusrat
2,2,S003,Tania Sarkar,Rajshahi,Dr. Siddique,78.0,41.0,75.0,194.0,False,Tania
3,3,S004,Rana Bhuiyan,Rangpur,NaN,NaN,77.0,57.0,NaN,True,Rana
4,4,S005,Arman Rahman,Rangpur,Ms. Ayesha,57.0,49.0,53.0,159.0,False,Arman
5,5,S006,Fahim Khan,Chattogram,Ms. Ayesha,46.0,NaN,94.0,NaN,False,Fahim
6,6,S007,Joy Roy,Sylhet,Mr. Karim,86.0,69.0,74.0,229.0,False,Joy
7,7,S008,Nusrat Ahmed,Chattogram,Dr. Siddique,58.0,93.0,80.0,231.0,True,Nusrat
8,8,S009,Mona Chowdhury,NaN,Dr. Siddique,NaN,42.0,NaN,NaN,False,Mona
9,9,S010,Kamal Islam,Chattogram,Mr. Karim,95.0,NaN,64.0,NaN,False,Kamal
10,10,S011,Sabrina Hasan,Barishal,Mr. Karim,NaN,62.0,53.0,NaN,False,Sabrina
11,11,S012,Sabrina Khan,Khulna,Dr. Siddique,86.0,55.0,50.0,191.0,False,Sabrina
12,12,S013,Tanvir Ahmed,Sylhet,Dr. Siddique,84.0,75.0,54.0,213.0,True,Tanvir
13,13,S014,Fahim Hossain,Rajshahi,Mr. Karim,91.0,NaN,65.0,NaN,False,Fahim
14,14,S015,Sabrina Khan,Rajshahi,Dr. Siddique,96.0,85.0,NaN,NaN,True,Sabrina
15,15,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana
16,16,S017,Samir Sarkar,NaN,Dr. Siddique,77.0,67.0,97.0,241.0,False,Samir
17,17,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
18,18,S019,Tania Hossain,Chattogram,Mr. Karim,80.0,50.0,90.0,220.0,False,Tania
19,19,S020,Nabila Roy,Chattogram,Ms. Ayesha,64.0,78.0,69.0,211.0,True,Nabila
20,20,S001,Nusrat Hossain,Sylhet,NaN,54.0,48.0,NaN,NaN,False,Nusrat
21,21,S018,Rashed Ahmed,NaN,NaN,48.0,72.0,71.0,191.0,True,Rashed
22,22,S016,Rana Hasan,Rangpur,Dr. Siddique,69.0,49.0,56.0,174.0,False,Rana

In [ ]:
group=data.groupby('Instructor')#akjon student ar under a koto jon student ase tader details dekhabe
group.sum()

,Unnamed: 0,ID,StudentName,District,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
Instructor,,,,,,,,,,
Dr. Siddique,108,S002S003S008S009S012S013S015S016S017S016,Nusrat BhuiyanTania SarkarNusrat AhmedMona Cho...,ChattogramRajshahiChattogramKhulnaSylhetRajsha...,684.0,598.0,509.0,1568.0,3,NusratTaniaNusratMonaSabrinaTanvirSabrinaRanaS...
Mr. Karim,56,S007S010S011S014S019,Joy RoyKamal IslamSabrina HasanFahim HossainTa...,SylhetChattogramBarishalRajshahiChattogram,352.0,181.0,346.0,449.0,0,JoyKamalSabrinaFahimTania
Ms. Ayesha,28,S005S006S020,Arman RahmanFahim KhanNabila Roy,RangpurChattogramChattogram,167.0,127.0,216.0,370.0,1,ArmanFahimNabila

In [ ]:
group.first()#instructor ar under ar first student gula dekhabe

,Unnamed: 0,ID,StudentName,District,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
Instructor,,,,,,,,,,
Dr. Siddique,1,S002,Nusrat Bhuiyan,Chattogram,67.0,42.0,41.0,150.0,False,Nusrat
Mr. Karim,6,S007,Joy Roy,Sylhet,86.0,69.0,74.0,229.0,False,Joy
Ms. Ayesha,4,S005,Arman Rahman,Rangpur,57.0,49.0,53.0,159.0,False,Arman

In [ ]:
group.last()#last student gula dekhabe group ar under ar

,Unnamed: 0,ID,StudentName,District,Math_Mark,Biology_Mark,Physics_Mark,totall_mark,Passed_In_Bio,First_name
Instructor,,,,,,,,,,
Dr. Siddique,22,S016,Rana Hasan,Rangpur,69.0,49.0,56.0,174.0,False,Rana
Mr. Karim,18,S019,Tania Hossain,Chattogram,80.0,50.0,90.0,220.0,False,Tania
Ms. Ayesha,19,S020,Nabila Roy,Chattogram,64.0,78.0,69.0,211.0,True,Nabila