In [1]:
##dataframe
import pandas as pd
s=pd.Series([10,20,30,40],index=[2,3,4,5])
s1=pd.Series(['a','b','c','d'],index=[5,4,3,2])
df=pd.DataFrame({'number':s,'letter':s1})
df

   number letter
2      10      d
3      20      c
4      30      b
5      40      a

In [3]:
##dataframe
data1={
    'name':['arman','tamim','shawon'],
    'age':[25,23,45],
    'city':['dhaka','ctg','col']
}
df=pd.DataFrame(data1)
df

     name  age   city
0   arman   25  dhaka
1   tamim   23    ctg
2  shawon   45    col

In [ ]:
#dataframe 3 list dictionart
data2=[
    {'name':'arman1','age':23,'city':'dhaka'},
       {'name':'arman2','age':22,'city':'savar'},
          {'name':'arman5','age':25,'city':'dhaka'},
             {'name':'arman4','age':26,'city':'dhaka'}
]
df2=pd.DataFrame(data2,index=['a','b','c','d'])
df2

    name  age   city
a  arman   23  dhaka
b  arman   23  dhaka
c  arman   23  dhaka
d  arman   23  dhaka

In [12]:
#add new column
df2['salary'] = [1000, 2000, 4000, 5000]
df2

    name  age   city  salary
a  arman   23  dhaka    1000
b  arman   23  dhaka    2000
c  arman   23  dhaka    4000
d  arman   23  dhaka    5000

In [14]:
df2['age']=df2['age']+10
df2

    name  age   city  salary
a  arman   33  dhaka    1000
b  arman   33  dhaka    2000
c  arman   33  dhaka    4000
d  arman   33  dhaka    5000