PANDAS

PHITRON PANDAS BASIC

In [1]:
print('hello world')

hello world

In [2]:
import pandas as pd
print('ok baby pandas is install here ')

ok baby pandas is install here

1.df=pd.read_csv('csv_file_name.csv')

there are 3 types of file 
1.csv

2.excel_file

3.parquet_file

4.Json_file(java script object notetation file)

*different file loading in pandas 

->csv_data=pd.read_csv('student.csv')

->excel_file=pd.read_excel('student.xlsx')

->parquet_file=pd.read_parquet("student.parquet")

->json=pd.read_json('student.json')

COLUMN IS CALLED FEATURE AND ROW IS CALLED SAMPLE

PANDAS DATA FRAME FROM INBUILT DATASTRUCTURE

In [3]:
#from list to dataframe create
mylst=[['arman',25],['Bob',30]]#list in list tecnique
list_dataframe=pd.DataFrame(mylst)
list_dataframe

       0   1
0  arman  25
1    Bob  30

#from tuple to dataframe create

In [4]:
tup=(('arman',25),('shawon',20))
tup_df=pd.DataFrame(tup)
tup_df

        0   1
0   arman  25
1  shawon  20

DICTIONARY TO DATAFRAME

In [5]:
Dic={
     'Name':['Arman','Bob',"hossain"],
     "age":[25,56,89]
}
dict=pd.DataFrame(Dic)
dict

      Name  age
0    Arman   25
1      Bob   56
2  hossain   89

In [6]:
Dic={
     'Name':['Arman','Bob',"hossain"],
     "age":[25,56,89,90]#here show an error because in this key and value dont 
     #mathch each other so that it show error
}
dict=pd.DataFrame(Dic)
dict

ValueError: All arrays must be of the same length

In [ ]:
#another way to crete a dataframe in dictionary
my_data=[
      {'name':'arman','age':24,'city':"dhaka"},
      {'name':'arman2','age':56,'city':"london","area":"uk"}#here it dont show error when value is not here give NaN
]
data=pd.DataFrame(my_data)
data

     name  age    city area
0   arman   24   dhaka  NaN
1  arman2   56  london   uk

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")

Sample Data Created and Saved as employees.csv

In [ ]:
df=pd.read_csv("employees.csv")
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

pandas basic functionalities

In [ ]:
df.head()#prothom diker koyta value dekhabe shudu

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

In [ ]:
df.head(3)#3 ta head dekhabe shudu

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance

In [ ]:
df.tail()#last ar diker koyta value dekhabe shudu

   id  age  salary     dept
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df.tail(3)#last ar diker only 3 ta value dekha

   id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR

In [ ]:
#we only see one  column name in this function
df.columns

Index(['id', 'age', 'salary', 'dept'], dtype='object')

In [ ]:
col=list(df.columns)#we can see column name as List 
col

['id', 'age', 'salary', 'dept']

In [ ]:
#we also see column name as a matrix
col1=np.array(df.columns)
col1

array(['id', 'age', 'salary', 'dept'], dtype=object)

In [ ]:
#we want see index in this csv_file like an array
ind=np.array(df.index)
ind

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#we want to see all information of this file 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   age     10 non-null     int64
 2   salary  10 non-null     int64
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

In [ ]:
#if we want to see in this dataframe randomly some sample any row 
#we print sample(5) when we run it  it show us the sample data of any place 
#when we run it in multiple time it automatically change 
df.sample(5)#every time it show us different types of value in 5 rows

   id  age  salary     dept
8   9   28   32433    Sales
2   3   32   46023  Finance
5   6   56   30769    Sales
7   8   40   86101       IT
3   4   25   71090       IT

In [ ]:
#staticall value we want to see
df.describe()#show all staticall information of this csv file shudu float data gular information dekhabe

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

#accesing values from dataFrame

df['id']

In [ ]:
df['id']#accesing id column

(0     1
 1     2
 2     3
 3     4
 4     5
 5     6
 6     7
 7     8
 8     9
 9    10
 Name: id, dtype: int64,
 ['age'])

In [ ]:
type(df["id"])

pandas.core.series.Series

loc and iloc in python pandas series 

loc[row(index),column(feature)]

loc[start:end,col_start,col_end]

In [ ]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df.loc[0]#0 no index show all values of 0 no index

id            1
age          56
salary    77191
dept         HR
Name: 0, dtype: object

In [ ]:
type(df.loc[0])

pandas.core.series.Series

In [ ]:
#multiple row in normal list
df.loc[[2,3,9]]#2,3,9 no row will show
#joto pojonto limit dibo toto pojontoi dekhabe value row wise

   id  age  salary     dept
2   3   32   46023  Finance
3   4   25   71090       IT
9  10   28   35311       HR

In [ ]:
#multiple row (range())

df.loc[3:7]

   id  age  salary     dept
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT

In [ ]:
#single column dekhar jonno
df.loc[:,'salary']

0    77191
1    74131
2    46023
3    71090
4    31685
5    30769
6    89735
7    86101
8    32433
9    35311
Name: salary, dtype: int64

In [ ]:
#multiple column dekhar jonno

df.loc[:,['salary','dept']]

   salary     dept
0   77191       HR
1   74131       IT
2   46023  Finance
3   71090       IT
4   31685       HR
5   30769    Sales
6   89735  Finance
7   86101       IT
8   32433    Sales
9   35311       HR

In [ ]:
#row with column dekhar jonno

df.loc[3:5,'dept']#shudu akta column e dekhabe multiple colmun dekhabe na single column

3       IT
4       HR
5    Sales
Name: dept, dtype: object

iloc in python programming language in details

Changing index and column using iloc method in pandas

In [8]:
df=pd.read_csv('employees.csv')
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [9]:
df_idx=df.set_index('dept')#ai khan dept gula idx hoye gese
df_idx

         id  age  salary
dept
HR        1   56   77191
IT        2   46   74131
Finance   3   32   46023
IT        4   25   71090
HR        5   38   31685
Sales     6   56   30769
Finance   7   36   89735
IT        8   40   86101
Sales     9   28   32433
HR       10   28   35311

In [10]:
df_idx=df.iloc[[3,4]]#here index is dept which is non numerical value but we know that loc only take numeriacla value
df_idx

   id  age  salary dept
3   4   25   71090   IT
4   5   38   31685   HR

In [11]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [12]:
#so we can apply for this calculation use iloc value
df_idx=df.set_index('dept')

In [13]:
df_idx

         id  age  salary
dept
HR        1   56   77191
IT        2   46   74131
Finance   3   32   46023
IT        4   25   71090
HR        5   38   31685
Sales     6   56   30769
Finance   7   36   89735
IT        8   40   86101
Sales     9   28   32433
HR       10   28   35311

In [16]:
df_idx=df.loc[3:5]
df_idx

   id  age  salary   dept
3   4   25   71090     IT
4   5   38   31685     HR
5   6   56   30769  Sales

In [18]:
df_idx=df.iloc[3:5]
df_idx

   id  age  salary dept
3   4   25   71090   IT
4   5   38   31685   HR

In [19]:
df_idx.iloc[:,0:4]

   id  age  salary dept
3   4   25   71090   IT
4   5   38   31685   HR

In [20]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df2=df.rename(columns={'id':'HR_ID'})#rename ID to HR_ID
df2

   HR_ID  age  salary     dept
0      1   56   77191       HR
1      2   46   74131       IT
2      3   32   46023  Finance
3      4   25   71090       IT
4      5   38   31685       HR
5      6   56   30769    Sales
6      7   36   89735  Finance
7      8   40   86101       IT
8      9   28   32433    Sales
9     10   28   35311       HR

In [ ]:
df.drop(0)#drow 0 no index value

   id  age  salary     dept
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [24]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [25]:
df.drop('id',axis=1)

   age  salary     dept
0   56   77191       HR
1   46   74131       IT
2   32   46023  Finance
3   25   71090       IT
4   38   31685       HR
5   56   30769    Sales
6   36   89735  Finance
7   40   86101       IT
8   28   32433    Sales
9   28   35311       HR

In [26]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [28]:
#we want to change a column specific value by this 
df.loc[1,'dept']='ML Engineer'
df

   id  age  salary         dept
0   1   56   77191           HR
1   2   46   74131  ML Engineer
2   3   32   46023      Finance
3   4   25   71090           IT
4   5   38   31685           HR
5   6   56   30769        Sales
6   7   36   89735      Finance
7   8   40   86101           IT
8   9   28   32433        Sales
9  10   28   35311           HR

In [29]:
#we wantto change salary
df.loc[1:3,'salary']+=2000#here sum 2000 to one to three column salary value
df

   id  age  salary         dept
0   1   56   77191           HR
1   2   46   76131  ML Engineer
2   3   32   48023      Finance
3   4   25   73090           IT
4   5   38   31685           HR
5   6   56   30769        Sales
6   7   36   89735      Finance
7   8   40   86101           IT
8   9   28   32433        Sales
9  10   28   35311           HR

In [ ]:
#iterator in python pandas 
for i,series in df.iterrows():#row wise itter korbe 
    print(f'{i}:{series}')

0:id            1
age          56
salary    77191
dept         HR
Name: 0, dtype: object
1:id                  2
age                46
salary          76131
dept      ML Engineer
Name: 1, dtype: object
2:id              3
age            32
salary      48023
dept      Finance
Name: 2, dtype: object
3:id            4
age          25
salary    73090
dept         IT
Name: 3, dtype: object
4:id            5
age          38
salary    31685
dept         HR
Name: 4, dtype: object
5:id            6
age          56
salary    30769
dept      Sales
Name: 5, dtype: object
6:id              7
age            36
salary      89735
dept      Finance
Name: 6, dtype: object
7:id            8
age          40
salary    86101
dept         IT
Name: 7, dtype: object
8:id            9
age          28
salary    32433
dept      Sales
Name: 8, dtype: object
9:id           10
age          28
salary    35311
dept         HR
Name: 9, dtype: object

In [31]:
#itter as a tuples
for i in df.itertuples():
    print(i)

Pandas(Index=0, id=1, age=56, salary=77191, dept='HR')
Pandas(Index=1, id=2, age=46, salary=76131, dept='ML Engineer')
Pandas(Index=2, id=3, age=32, salary=48023, dept='Finance')
Pandas(Index=3, id=4, age=25, salary=73090, dept='IT')
Pandas(Index=4, id=5, age=38, salary=31685, dept='HR')
Pandas(Index=5, id=6, age=56, salary=30769, dept='Sales')
Pandas(Index=6, id=7, age=36, salary=89735, dept='Finance')
Pandas(Index=7, id=8, age=40, salary=86101, dept='IT')
Pandas(Index=8, id=9, age=28, salary=32433, dept='Sales')
Pandas(Index=9, id=10, age=28, salary=35311, dept='HR')

SORTING IN PYTHON IN PANDAS

In [ ]:
df.sort_values('salary')#salary wise sort korbe (choto theke boro sort korbe )

   id  age  salary         dept
5   6   56   30769        Sales
4   5   38   31685           HR
8   9   28   32433        Sales
9  10   28   35311           HR
2   3   32   48023      Finance
3   4   25   73090           IT
1   2   46   76131  ML Engineer
0   1   56   77191           HR
7   8   40   86101           IT
6   7   36   89735      Finance

In [ ]:
df.sort_values('salary',ascending=False)#boro theke choto sort korbe

   id  age  salary         dept
6   7   36   89735      Finance
7   8   40   86101           IT
0   1   56   77191           HR
1   2   46   76131  ML Engineer
3   4   25   73090           IT
2   3   32   48023      Finance
9  10   28   35311           HR
8   9   28   32433        Sales
4   5   38   31685           HR
5   6   56   30769        Sales

In [35]:
df

   id  age  salary         dept
0   1   56   77191           HR
1   2   46   76131  ML Engineer
2   3   32   48023      Finance
3   4   25   73090           IT
4   5   38   31685           HR
5   6   56   30769        Sales
6   7   36   89735      Finance
7   8   40   86101           IT
8   9   28   32433        Sales
9  10   28   35311           HR

In [ ]:
df.sort_values(['salary','age'],ascending=[0,1])#salary  boro theke choto print hobe 0 ar jonno
#age choto theke boro print hobe 1 ar jonno

   id  age  salary         dept
6   7   36   89735      Finance
7   8   40   86101           IT
0   1   56   77191           HR
1   2   46   76131  ML Engineer
3   4   25   73090           IT
2   3   32   48023      Finance
9  10   28   35311           HR
8   9   28   32433        Sales
4   5   38   31685           HR
5   6   56   30769        Sales

FILTERING DATA ON CONDITION

In [ ]:
not_started=df.loc[df['dept']=='HR']#jara hr tader tai shudu print korbe 
not_started

   id  age  salary dept
0   1   56   77191   HR
4   5   38   31685   HR
9  10   28   35311   HR

In [45]:
#jara hr department a job kore and jader salary 50000 ar niche tader value e shudu print korbe 
a=df.loc[(df["dept"]=="HR")&(df["salary"]<50000)]
a

   id  age  salary dept
4   5   38   31685   HR
9  10   28   35311   HR