PANDAS

PHITRON PANDAS BASIC

In [1]:
print('hello world')

hello world

In [1]:
import pandas as pd
print('ok baby pandas is install here ')

ok baby pandas is install here

1.df=pd.read_csv('csv_file_name.csv')

there are 3 types of file 
1.csv

2.excel_file

3.parquet_file

4.Json_file(java script object notetation file)

*different file loading in pandas 

->csv_data=pd.read_csv('student.csv')

->excel_file=pd.read_excel('student.xlsx')

->parquet_file=pd.read_parquet("student.parquet")

->json=pd.read_json('student.json')

COLUMN IS CALLED FEATURE AND ROW IS CALLED SAMPLE

PANDAS DATA FRAME FROM INBUILT DATASTRUCTURE

In [4]:
#from list to dataframe create
mylst=[['arman',25],['Bob',30]]#list in list tecnique
list_dataframe=pd.DataFrame(mylst)
list_dataframe

       0   1
0  arman  25
1    Bob  30

#from tuple to dataframe create

In [4]:
tup=(('arman',25),('shawon',20))
tup_df=pd.DataFrame(tup)
tup_df

        0   1
0   arman  25
1  shawon  20

DICTIONARY TO DATAFRAME

In [5]:
Dic={
     'Name':['Arman','Bob',"hossain"],
     "age":[25,56,89]
}
dict=pd.DataFrame(Dic)
dict

      Name  age
0    Arman   25
1      Bob   56
2  hossain   89

In [6]:
Dic={
     'Name':['Arman','Bob',"hossain"],
     "age":[25,56,89,90]#here show an error because in this key and value dont 
     #mathch each other so that it show error
}
dict=pd.DataFrame(Dic)
dict

ValueError: All arrays must be of the same length

In [ ]:
#another way to crete a dataframe in dictionary
my_data=[
      {'name':'arman','age':24,'city':"dhaka"},
      {'name':'arman2','age':56,'city':"london","area":"uk"}#here it dont show error when value is not here give NaN
]
data=pd.DataFrame(my_data)
data

     name  age    city area
0   arman   24   dhaka  NaN
1  arman2   56  london   uk

In [8]:
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")

Sample Data Created and Saved as employees.csv

In [9]:
df=pd.read_csv("employees.csv")
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

pandas basic functionalities

In [ ]:
df.head()#prothom diker koyta value dekhabe shudu

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

In [ ]:
df.head(3)#3 ta head dekhabe shudu

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance

In [ ]:
df.tail()#last ar diker koyta value dekhabe shudu

   id  age  salary     dept
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df.tail(3)#last ar diker only 3 ta value dekha

   id  age  salary   dept
7   8   40   86101     IT
8   9   28   32433  Sales
9  10   28   35311     HR

In [ ]:
#we only see one  column name in this function
df.columns

Index(['id', 'age', 'salary', 'dept'], dtype='object')

In [ ]:
col=list(df.columns)#we can see column name as List 
col

['id', 'age', 'salary', 'dept']

In [ ]:
#we also see column name as a matrix
col1=np.array(df.columns)
col1

array(['id', 'age', 'salary', 'dept'], dtype=object)

In [ ]:
#we want see index in this csv_file like an array
ind=np.array(df.index)
ind

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#we want to see all information of this file 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   age     10 non-null     int64
 2   salary  10 non-null     int64
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes

In [ ]:
#if we want to see in this dataframe randomly some sample any row 
#we print sample(5) when we run it  it show us the sample data of any place 
#when we run it in multiple time it automatically change 
df.sample(5)#every time it show us different types of value in 5 rows

   id  age  salary     dept
8   9   28   32433    Sales
2   3   32   46023  Finance
5   6   56   30769    Sales
7   8   40   86101       IT
3   4   25   71090       IT

In [ ]:
#staticall value we want to see
df.describe()#show all staticall information of this csv file shudu float data gular information dekhabe

             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

#accesing values from dataFrame

df['id']

In [ ]:
df['id']#accesing id column

(0     1
 1     2
 2     3
 3     4
 4     5
 5     6
 6     7
 7     8
 8     9
 9    10
 Name: id, dtype: int64,
 ['age'])

In [ ]:
type(df["id"])

pandas.core.series.Series

loc and iloc in python pandas series 

loc[row(index),column(feature)]

loc[start:end,col_start,col_end]

In [ ]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df.loc[0]#0 no index show all values of 0 no index

id            1
age          56
salary    77191
dept         HR
Name: 0, dtype: object

In [ ]:
type(df.loc[0])

pandas.core.series.Series

In [ ]:
#multiple row in normal list
df.loc[[2,3,9]]#2,3,9 no row will show
#joto pojonto limit dibo toto pojontoi dekhabe value row wise

   id  age  salary     dept
2   3   32   46023  Finance
3   4   25   71090       IT
9  10   28   35311       HR

In [ ]:
#multiple row (range())

df.loc[3:7]

   id  age  salary     dept
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT

In [ ]:
#single column dekhar jonno
df.loc[:,'salary']

0    77191
1    74131
2    46023
3    71090
4    31685
5    30769
6    89735
7    86101
8    32433
9    35311
Name: salary, dtype: int64

In [ ]:
#multiple column dekhar jonno

df.loc[:,['salary','dept']]

   salary     dept
0   77191       HR
1   74131       IT
2   46023  Finance
3   71090       IT
4   31685       HR
5   30769    Sales
6   89735  Finance
7   86101       IT
8   32433    Sales
9   35311       HR

In [ ]:
#row with column dekhar jonno

df.loc[3:5,'dept']#shudu akta column e dekhabe multiple colmun dekhabe na single column

3       IT
4       HR
5    Sales
Name: dept, dtype: object

iloc in python programming language in details

Changing index and column using iloc method in pandas

In [ ]:
df=pd.read_csv('employees.csv')
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df_idx=df.set_index('dept')#ai khan dept gula idx hoye gese
df_idx

         id  age  salary
dept
HR        1   56   77191
IT        2   46   74131
Finance   3   32   46023
IT        4   25   71090
HR        5   38   31685
Sales     6   56   30769
Finance   7   36   89735
IT        8   40   86101
Sales     9   28   32433
HR       10   28   35311

In [ ]:
df_idx=df.iloc[[3,4]]#here index is dept which is non numerical value but we know that loc only take numeriacla value
df_idx

   id  age  salary dept
3   4   25   71090   IT
4   5   38   31685   HR

In [ ]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
#so we can apply for this calculation use iloc value
df_idx=df.set_index('dept')

In [ ]:
df_idx

         id  age  salary
dept
HR        1   56   77191
IT        2   46   74131
Finance   3   32   46023
IT        4   25   71090
HR        5   38   31685
Sales     6   56   30769
Finance   7   36   89735
IT        8   40   86101
Sales     9   28   32433
HR       10   28   35311

In [ ]:
df_idx=df.loc[3:5]
df_idx

   id  age  salary   dept
3   4   25   71090     IT
4   5   38   31685     HR
5   6   56   30769  Sales

In [ ]:
df_idx=df.iloc[3:5]
df_idx

   id  age  salary dept
3   4   25   71090   IT
4   5   38   31685   HR

In [ ]:
df_idx.iloc[:,0:4]

   id  age  salary dept
3   4   25   71090   IT
4   5   38   31685   HR

In [ ]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df2=df.rename(columns={'id':'HR_ID'})#rename ID to HR_ID
df2

   HR_ID  age  salary     dept
0      1   56   77191       HR
1      2   46   74131       IT
2      3   32   46023  Finance
3      4   25   71090       IT
4      5   38   31685       HR
5      6   56   30769    Sales
6      7   36   89735  Finance
7      8   40   86101       IT
8      9   28   32433    Sales
9     10   28   35311       HR

In [ ]:
df.drop(0)#drow 0 no index value

   id  age  salary     dept
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
df.drop('id',axis=1)

   age  salary     dept
0   56   77191       HR
1   46   74131       IT
2   32   46023  Finance
3   25   71090       IT
4   38   31685       HR
5   56   30769    Sales
6   36   89735  Finance
7   40   86101       IT
8   28   32433    Sales
9   28   35311       HR

In [ ]:
df

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [ ]:
#we want to change a column specific value by this 
df.loc[1,'dept']='ML Engineer'
df

   id  age  salary         dept
0   1   56   77191           HR
1   2   46   74131  ML Engineer
2   3   32   46023      Finance
3   4   25   71090           IT
4   5   38   31685           HR
5   6   56   30769        Sales
6   7   36   89735      Finance
7   8   40   86101           IT
8   9   28   32433        Sales
9  10   28   35311           HR

In [ ]:
#we wantto change salary
df.loc[1:3,'salary']+=2000#here sum 2000 to one to three column salary value
df

   id  age  salary         dept
0   1   56   77191           HR
1   2   46   76131  ML Engineer
2   3   32   48023      Finance
3   4   25   73090           IT
4   5   38   31685           HR
5   6   56   30769        Sales
6   7   36   89735      Finance
7   8   40   86101           IT
8   9   28   32433        Sales
9  10   28   35311           HR

In [ ]:
#iterator in python pandas 
for i,series in df.iterrows():#row wise itter korbe 
    print(f'{i}:{series}')

0:id            1
age          56
salary    77191
dept         HR
Name: 0, dtype: object
1:id                  2
age                46
salary          76131
dept      ML Engineer
Name: 1, dtype: object
2:id              3
age            32
salary      48023
dept      Finance
Name: 2, dtype: object
3:id            4
age          25
salary    73090
dept         IT
Name: 3, dtype: object
4:id            5
age          38
salary    31685
dept         HR
Name: 4, dtype: object
5:id            6
age          56
salary    30769
dept      Sales
Name: 5, dtype: object
6:id              7
age            36
salary      89735
dept      Finance
Name: 6, dtype: object
7:id            8
age          40
salary    86101
dept         IT
Name: 7, dtype: object
8:id            9
age          28
salary    32433
dept      Sales
Name: 8, dtype: object
9:id           10
age          28
salary    35311
dept         HR
Name: 9, dtype: object

In [ ]:
#itter as a tuples
for i in df.itertuples():
    print(i)

Pandas(Index=0, id=1, age=56, salary=77191, dept='HR')
Pandas(Index=1, id=2, age=46, salary=76131, dept='ML Engineer')
Pandas(Index=2, id=3, age=32, salary=48023, dept='Finance')
Pandas(Index=3, id=4, age=25, salary=73090, dept='IT')
Pandas(Index=4, id=5, age=38, salary=31685, dept='HR')
Pandas(Index=5, id=6, age=56, salary=30769, dept='Sales')
Pandas(Index=6, id=7, age=36, salary=89735, dept='Finance')
Pandas(Index=7, id=8, age=40, salary=86101, dept='IT')
Pandas(Index=8, id=9, age=28, salary=32433, dept='Sales')
Pandas(Index=9, id=10, age=28, salary=35311, dept='HR')

SORTING IN PYTHON IN PANDAS

In [ ]:
df.sort_values('salary')#salary wise sort korbe (choto theke boro sort korbe )

   id  age  salary         dept
5   6   56   30769        Sales
4   5   38   31685           HR
8   9   28   32433        Sales
9  10   28   35311           HR
2   3   32   48023      Finance
3   4   25   73090           IT
1   2   46   76131  ML Engineer
0   1   56   77191           HR
7   8   40   86101           IT
6   7   36   89735      Finance

In [ ]:
df.sort_values('salary',ascending=False)#boro theke choto sort korbe

   id  age  salary         dept
6   7   36   89735      Finance
7   8   40   86101           IT
0   1   56   77191           HR
1   2   46   76131  ML Engineer
3   4   25   73090           IT
2   3   32   48023      Finance
9  10   28   35311           HR
8   9   28   32433        Sales
4   5   38   31685           HR
5   6   56   30769        Sales

In [ ]:
df

   id  age  salary         dept
0   1   56   77191           HR
1   2   46   76131  ML Engineer
2   3   32   48023      Finance
3   4   25   73090           IT
4   5   38   31685           HR
5   6   56   30769        Sales
6   7   36   89735      Finance
7   8   40   86101           IT
8   9   28   32433        Sales
9  10   28   35311           HR

In [ ]:
df.sort_values(['salary','age'],ascending=[0,1])#salary  boro theke choto print hobe 0 ar jonno
#age choto theke boro print hobe 1 ar jonno

   id  age  salary         dept
6   7   36   89735      Finance
7   8   40   86101           IT
0   1   56   77191           HR
1   2   46   76131  ML Engineer
3   4   25   73090           IT
2   3   32   48023      Finance
9  10   28   35311           HR
8   9   28   32433        Sales
4   5   38   31685           HR
5   6   56   30769        Sales

FILTERING DATA ON CONDITION

In [ ]:
not_started=df.loc[df['dept']=='HR']#jara hr tader tai shudu print korbe 
not_started

   id  age  salary dept
0   1   56   77191   HR
4   5   38   31685   HR
9  10   28   35311   HR

In [ ]:
#jara hr department a job kore and jader salary 50000 ar niche tader value e shudu print korbe 
a=df.loc[(df["dept"]=="HR")&(df["salary"]<50000)]
a

   id  age  salary dept
4   5   38   31685   HR
9  10   28   35311   HR

In [ ]:
df=pd.read_csv('data.csv')
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
#last ar value
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

totall 50 ta row value totall 47 so null is 3 and sales null is 4

In [ ]:
df.dtypes#column ar type bolbe sob amader

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [ ]:
df.isnull()#null na paile false return korbe paile true return korbe

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [ ]:
df.isnull().sum()#koyta null ase kon column a seta show korbe

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
#null gulate te amra value bosaiya dibo
df.fillna(0)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
#new column 
df['sales report']=df['Sales'].fillna(77777)
df#sames column ar jeikhan a null silo oikhan a new column create kore new value bosbe 77777
#amra chaile null ar jaigay sales column ar totall mean bosate pari 
df['sales report']= df['Sales'].fillna(df['Sales'].mean())
df#null ar jaigay mean value bose jabe

          Date Category  Value   Product  Sales Region  sales report
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [ ]:
#rename column ar nam change korbooo
df1=df.rename(columns={'sales report':'new sales'})
df1

          Date Category  Value   Product  Sales Region   new sales
0   2023-01-01        A   28.0  Product1  754.0   East  754.000000
1   2023-01-02        B   39.0  Product3  110.0  North  110.000000
2   2023-01-03        C   32.0  Product2  398.0   East  398.000000
3   2023-01-04        B    8.0  Product1  522.0   East  522.000000
4   2023-01-05        B   26.0  Product3  869.0  North  869.000000
5   2023-01-06        B   54.0  Product3  192.0   West  192.000000
6   2023-01-07        A   16.0  Product1  936.0   East  936.000000
7   2023-01-08        C   89.0  Product1  488.0   West  488.000000
8   2023-01-09        C   37.0  Product3  772.0   West  772.000000
9   2023-01-10        A   22.0  Product2  834.0   West  834.000000
10  2023-01-11        B    7.0  Product1  842.0  North  842.000000
11  2023-01-12        B   60.0  Product2    NaN   West  557.130435
12  2023-01-13        A   70.0  Product3  628.0  South  628.000000
13  2023-01-14        A   69.0  Product1  423.0   East  423.000000
14  2023-01-15        A   47.0  Product2  893.0   West  893.000000
15  2023-01-16        C    NaN  Product1  895.0  North  895.000000
16  2023-01-17        C   93.0  Product2  511.0  South  511.000000
17  2023-01-18        C    NaN  Product1  108.0   West  108.000000
18  2023-01-19        A   31.0  Product2  578.0   West  578.000000
19  2023-01-20        A   59.0  Product1  736.0   East  736.000000
20  2023-01-21        C   82.0  Product3  606.0  South  606.000000
21  2023-01-22        C   37.0  Product2  992.0  South  992.000000
22  2023-01-23        B   62.0  Product3  942.0  North  942.000000
23  2023-01-24        C   92.0  Product2  342.0   West  342.000000
24  2023-01-25        A   24.0  Product2  458.0   East  458.000000
25  2023-01-26        C   95.0  Product1  584.0   West  584.000000
26  2023-01-27        C   71.0  Product2  619.0  North  619.000000
27  2023-01-28        C   56.0  Product2  224.0  North  224.000000
28  2023-01-29        B    NaN  Product3  617.0  North  617.000000
29  2023-01-30        C   51.0  Product2  737.0  South  737.000000
30  2023-01-31        B   50.0  Product3  735.0   West  735.000000
31  2023-02-01        A   17.0  Product2  189.0   West  189.000000
32  2023-02-02        B   63.0  Product3  338.0  South  338.000000
33  2023-02-03        C   27.0  Product3    NaN   East  557.130435
34  2023-02-04        C   70.0  Product3  669.0   West  669.000000
35  2023-02-05        B   60.0  Product2    NaN   West  557.130435
36  2023-02-06        C   36.0  Product3  177.0   East  177.000000
37  2023-02-07        C    2.0  Product1    NaN  North  557.130435
38  2023-02-08        C   94.0  Product1  408.0  South  408.000000
39  2023-02-09        A   62.0  Product1  155.0   West  155.000000
40  2023-02-10        B   15.0  Product1  578.0   East  578.000000
41  2023-02-11        C   97.0  Product1  256.0   East  256.000000
42  2023-02-12        A   93.0  Product3  164.0   West  164.000000
43  2023-02-13        A   43.0  Product3  949.0   East  949.000000
44  2023-02-14        A   96.0  Product3  830.0   East  830.000000
45  2023-02-15        B   99.0  Product2  599.0   West  599.000000
46  2023-02-16        B    6.0  Product1  938.0  South  938.000000
47  2023-02-17        B   69.0  Product3  143.0   West  143.000000
48  2023-02-18        C   65.0  Product3  182.0  North  182.000000
49  2023-02-19        C   11.0  Product3  708.0  North  708.000000

In [ ]:
df['value2x']=df['Value'].apply(lambda x:x*2)
df#here cteate hobe new column and sei column a value*2 hoye bosbe

          Date Category  Value   Product  Sales Region  sales report  value2x
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000     56.0
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000     78.0
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000     64.0
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000     16.0
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000     52.0
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000    108.0
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000     32.0
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000    178.0
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000     74.0
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000     44.0
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000     14.0
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435    120.0
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000    140.0
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000    138.0
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000     94.0
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000      NaN
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000    186.0
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000      NaN
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000     62.0
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000    118.0
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000    164.0
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000     74.0
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000    124.0
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000    184.0
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000     48.0
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000    190.0
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000    142.0
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000    112.0
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000      NaN
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000    102.0
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000    100.0
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000     34.0
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000    126.0
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435     54.0
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000    140.0
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435    120.0
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000     72.0
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435      4.0
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000    188.0
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000    124.0
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000     30.0
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000    194.0
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000    186.0
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000     86.0
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000    192.0
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000    198.0
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000     12.0
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000    138.0
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000    130.0
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000     22.0

In [ ]:
df

          Date Category  Value   Product  Sales Region  sales report  value2x
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000     56.0
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000     78.0
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000     64.0
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000     16.0
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000     52.0
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000    108.0
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000     32.0
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000    178.0
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000     74.0
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000     44.0
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000     14.0
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435    120.0
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000    140.0
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000    138.0
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000     94.0
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000      NaN
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000    186.0
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000      NaN
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000     62.0
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000    118.0
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000    164.0
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000     74.0
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000    124.0
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000    184.0
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000     48.0
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000    190.0
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000    142.0
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000    112.0
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000      NaN
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000    102.0
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000    100.0
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000     34.0
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000    126.0
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435     54.0
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000    140.0
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435    120.0
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000     72.0
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435      4.0
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000    188.0
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000    124.0
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000     30.0
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000    194.0
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000    186.0
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000     86.0
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000    192.0
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000    198.0
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000     12.0
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000    138.0
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000    130.0
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000     22.0

SORTING

In [ ]:
df.sort_values(['Value'],inplace=True)
df

          Date Category  Value   Product  Sales Region  sales report  value2x
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435      4.0
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000     12.0
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000     14.0
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000     16.0
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000     22.0
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000     30.0
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000     32.0
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000     34.0
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000     44.0
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000     48.0
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000     52.0
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435     54.0
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000     56.0
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000     62.0
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000     64.0
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000     72.0
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000     74.0
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000     74.0
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000     78.0
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000     86.0
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000     94.0
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000    100.0
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000    102.0
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000    108.0
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000    112.0
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000    118.0
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435    120.0
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435    120.0
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000    124.0
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000    124.0
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000    126.0
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000    130.0
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000    138.0
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000    138.0
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000    140.0
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000    140.0
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000    142.0
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000    164.0
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000    178.0
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000    184.0
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000    186.0
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000    186.0
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000    188.0
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000    190.0
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000    192.0
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000    194.0
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000    198.0
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000      NaN
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000      NaN
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000      NaN

In [ ]:
df[df['Category']=='A']#only print catagory a product

          Date Category  Value   Product  Sales Region  sales report  value2x
6   2023-01-07        A   16.0  Product1  936.0   East         936.0     32.0
31  2023-02-01        A   17.0  Product2  189.0   West         189.0     34.0
9   2023-01-10        A   22.0  Product2  834.0   West         834.0     44.0
24  2023-01-25        A   24.0  Product2  458.0   East         458.0     48.0
0   2023-01-01        A   28.0  Product1  754.0   East         754.0     56.0
18  2023-01-19        A   31.0  Product2  578.0   West         578.0     62.0
43  2023-02-13        A   43.0  Product3  949.0   East         949.0     86.0
14  2023-01-15        A   47.0  Product2  893.0   West         893.0     94.0
19  2023-01-20        A   59.0  Product1  736.0   East         736.0    118.0
39  2023-02-09        A   62.0  Product1  155.0   West         155.0    124.0
13  2023-01-14        A   69.0  Product1  423.0   East         423.0    138.0
12  2023-01-13        A   70.0  Product3  628.0  South         628.0    140.0
42  2023-02-12        A   93.0  Product3  164.0   West         164.0    186.0
44  2023-02-14        A   96.0  Product3  830.0   East         830.0    192.0

In [ ]:
df[(df['Category']=='A')&(df['Region']=="East")]
#catagory  A and region East shudu print korbe

          Date Category  Value   Product  Sales Region  sales report  value2x
6   2023-01-07        A   16.0  Product1  936.0   East         936.0     32.0
24  2023-01-25        A   24.0  Product2  458.0   East         458.0     48.0
0   2023-01-01        A   28.0  Product1  754.0   East         754.0     56.0
43  2023-02-13        A   43.0  Product3  949.0   East         949.0     86.0
19  2023-01-20        A   59.0  Product1  736.0   East         736.0    118.0
13  2023-01-14        A   69.0  Product1  423.0   East         423.0    138.0
44  2023-02-14        A   96.0  Product3  830.0   East         830.0    192.0

In [ ]:
#a chara  sob value dekhabe 
df[~(df['Category']=='A')]

          Date Category  Value   Product  Sales Region  sales report  value2x
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435      4.0
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000     12.0
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000     14.0
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000     16.0
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000     22.0
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000     30.0
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000     52.0
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435     54.0
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000     64.0
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000     72.0
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000     74.0
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000     74.0
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000     78.0
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000    100.0
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000    102.0
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000    108.0
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000    112.0
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435    120.0
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435    120.0
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000    124.0
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000    126.0
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000    130.0
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000    138.0
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000    140.0
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000    142.0
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000    164.0
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000    178.0
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000    184.0
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000    186.0
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000    188.0
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000    190.0
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000    194.0
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000    198.0
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000      NaN
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000      NaN
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000      NaN

In [ ]:
arr=df[df['Category']=='B']
arr
#now we can only print unique values 
arr=arr['Value'].unique()
arr#mow this is only shows the unique values only

array([ 6.,  7.,  8., 15., 26., 39., 50., 54., 60., 62., 63., 69., 99.,
       nan])

In [ ]:
arr=df[df['Category']=='B']
arr.drop_duplicates(subset=['Value'])#duplicate gula remove hoye jabe

          Date Category  Value   Product  Sales Region  sales report  value2x
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000     12.0
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000     14.0
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000     16.0
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000     30.0
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000     52.0
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000     78.0
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000    100.0
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000    108.0
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435    120.0
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000    124.0
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000    126.0
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000    138.0
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000    198.0
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000      NaN

Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type

. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [ ]:
import pandas as pd

In [ ]:
lst=[10,20,30,40,50]
df=pd.Series(lst)
df

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
df.dtype

dtype('int64')

In [ ]:
data=[
     {'name':'arman','age':23,"city":'Dhaka'},
     {'name':'rakib','age':34,"city":'Usa'},
     {'name':'shawon','age':45,"city":'londom'},
     {'name':'jibon','age':34,"city":'italy'},
]
df=pd.DataFrame(data,index=[10,20,30,50])
df

      name  age    city
10   arman   23   Dhaka
20   rakib   34     Usa
30  shawon   45  londom
50   jibon   34   italy



Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), 

and summary statistics (.describe()).

In [ ]:
r=df.shape
r

(4, 3)

In [ ]:
df.describe()

             age
count   4.000000
mean   34.000000
std     8.981462
min    23.000000
25%    31.250000
50%    34.000000
75%    36.750000
max    45.000000

Create a DataFrame using the dictionary below:


data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

Print .columns, .index. Access a single column and one full row

In [7]:

data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}
df=pd.DataFrame(data)
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [11]:
df['Product']

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

In [12]:
#access a full row
df.loc[1]

Product     Book
Price         50
Quantity      60
Name: 1, dtype: object

In [13]:
df.columns

Index(['Product', 'Price', 'Quantity'], dtype='object')

In [16]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
df.iloc[:1]

  Product  Price  Quantity
0     Pen     10       100

In [20]:
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [23]:
df.iloc[1:3,0:2]

  Product  Price
1    Book     50
2  Eraser      5

In [24]:
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [25]:
df.drop(2)

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
3  Pencil      7       150

In [26]:
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [27]:
df.sort_values(['Quantity'],ascending=True)

  Product  Price  Quantity
1    Book     50        60
0     Pen     10       100
3  Pencil      7       150
2  Eraser      5       200

In [29]:
df.sort_values(['Product'],ascending=True)

  Product  Price  Quantity
1    Book     50        60
2  Eraser      5       200
0     Pen     10       100
3  Pencil      7       150